import type { Category, Product, Order, User, Notification, AdminStats, Supplier, Driver, Route, PurchaseOrder, Promotion, PickList, GoodsReceipt } from "@/types";

export const CATEGORIES: Category[] = [
  { id: "cat-1", name: "Beverages", slug: "beverages", productCount: 48, isActive: true, sortOrder: 1, description: "Soft drinks, water, juice, energy drinks", imageUrl: "/images/cat-beverages.jpg" },
  { id: "cat-2", name: "Instant Noodles", slug: "instant-noodles", productCount: 24, isActive: true, sortOrder: 2, description: "All instant noodle brands and variants", imageUrl: "/images/cat-noodles.jpg" },
  { id: "cat-3", name: "Snacks & Chips", slug: "snacks", productCount: 56, isActive: true, sortOrder: 3, description: "Chips, crackers, biscuits, candies", imageUrl: "/images/cat-snacks.jpg" },
  { id: "cat-4", name: "Canned Goods", slug: "canned-goods", productCount: 38, isActive: true, sortOrder: 4, description: "Sardines, tuna, corned beef, spam", imageUrl: "/images/cat-canned.jpg" },
  { id: "cat-5", name: "Condiments & Sauces", slug: "condiments", productCount: 32, isActive: true, sortOrder: 5, description: "Soy sauce, vinegar, ketchup, cooking oil", imageUrl: "/images/cat-condiments.jpg" },
  { id: "cat-6", name: "Personal Care", slug: "personal-care", productCount: 44, isActive: true, sortOrder: 6, description: "Shampoo, soap, toothpaste, deodorant", imageUrl: "/images/cat-personal.jpg" },
  { id: "cat-7", name: "Coffee & Milo", slug: "coffee", productCount: 20, isActive: true, sortOrder: 7, description: "3-in-1 coffee, Milo, hot choco", imageUrl: "/images/cat-coffee.jpg" },
  { id: "cat-8", name: "Laundry & Cleaning", slug: "laundry", productCount: 28, isActive: true, sortOrder: 8, description: "Detergent, fabric conditioner, bleach, dishwashing", imageUrl: "/images/cat-laundry.jpg" },
];

export const PRODUCTS: Product[] = [
  // ── Beverages (cat-1) ──────────────────────────────────────────────────────
  {
    id: "prod-1",
    categoryId: "cat-1",
    name: "Coca-Cola Regular 330ml",
    slug: "coca-cola-330ml",
    brand: "Coca-Cola",
    unit: "can",
    unitSize: "330ml",
    price: 28,
    srp: 35,
    sku: "CC-330-REG",
    minOrderQty: 24,
    isActive: true,
    isFeatured: true,
    stock: 480,
    lowStockThreshold: 48,
    createdAt: "2024-01-01T00:00:00Z",
    description: "Classic Coca-Cola in 330ml can. 24 cans per case.",
    imageUrl: "https://images.unsplash.com/photo-1554866585-cd94860890b7?w=400&q=80&auto=format&fit=crop",
  },
  {
    id: "prod-9",
    categoryId: "cat-1",
    name: "Wilkins Pure Distilled Water 500ml",
    slug: "wilkins-500ml",
    brand: "Wilkins",
    unit: "bottle",
    unitSize: "500ml",
    price: 12,
    srp: 15,
    sku: "WLK-500-PUR",
    minOrderQty: 24,
    isActive: true,
    isFeatured: false,
    stock: 7,
    lowStockThreshold: 48,
    createdAt: "2024-01-01T00:00:00Z",
    description: "Wilkins distilled water, 500ml bottle.",
    imageUrl: "https://images.unsplash.com/photo-1548839140-29a749e1cf4d?w=400&q=80&auto=format&fit=crop",
  },
  {
    id: "prod-11",
    categoryId: "cat-1",
    name: "Royal True Orange 355ml",
    slug: "royal-true-orange-355ml",
    brand: "Royal",
    unit: "can",
    unitSize: "355ml",
    price: 26,
    srp: 32,
    sku: "RTO-355-CAN",
    minOrderQty: 24,
    isActive: true,
    isFeatured: false,
    stock: 288,
    lowStockThreshold: 48,
    createdAt: "2024-01-01T00:00:00Z",
    description: "Royal True Orange carbonated drink in 355ml can. 24 cans per case.",
    imageUrl: "https://images.unsplash.com/photo-1600271886742-f049cd451bba?w=400&q=80&auto=format&fit=crop",
  },
  {
    id: "prod-12",
    categoryId: "cat-1",
    name: "Sprite 330ml",
    slug: "sprite-330ml",
    brand: "Sprite",
    unit: "can",
    unitSize: "330ml",
    price: 28,
    srp: 35,
    sku: "SPR-330-CAN",
    minOrderQty: 24,
    isActive: true,
    isFeatured: false,
    stock: 384,
    lowStockThreshold: 48,
    createdAt: "2024-01-01T00:00:00Z",
    description: "Sprite lemon-lime carbonated drink in 330ml can. 24 cans per case.",
    imageUrl: "https://images.unsplash.com/photo-1625772299848-391b6a87d7b3?w=400&q=80&auto=format&fit=crop",
  },
  {
    id: "prod-13",
    categoryId: "cat-1",
    name: "C2 Cool & Clean Green Tea 500ml",
    slug: "c2-green-tea-500ml",
    brand: "C2",
    unit: "bottle",
    unitSize: "500ml",
    price: 18,
    srp: 23,
    sku: "C2-GTE-500",
    minOrderQty: 24,
    isActive: true,
    isFeatured: true,
    stock: 336,
    lowStockThreshold: 48,
    createdAt: "2024-01-01T00:00:00Z",
    description: "C2 Cool & Clean ready-to-drink green tea, 500ml bottle.",
    imageUrl: "https://images.unsplash.com/photo-1556679343-c7306c1976bc?w=400&q=80&auto=format&fit=crop",
  },
  {
    id: "prod-14",
    categoryId: "cat-1",
    name: "Gatorade Lemon-Lime 500ml",
    slug: "gatorade-lemon-lime-500ml",
    brand: "Gatorade",
    unit: "bottle",
    unitSize: "500ml",
    price: 38,
    srp: 48,
    sku: "GAT-LLM-500",
    minOrderQty: 24,
    isActive: true,
    isFeatured: false,
    stock: 192,
    lowStockThreshold: 24,
    createdAt: "2024-01-01T00:00:00Z",
    description: "Gatorade sports drink in lemon-lime flavor, 500ml bottle.",
    imageUrl: "https://images.unsplash.com/photo-1563227812-0ea4c22e6cc8?w=400&q=80&auto=format&fit=crop",
  },

  // ── Instant Noodles (cat-2) ───────────────────────────────────────────────
  {
    id: "prod-2",
    categoryId: "cat-2",
    name: "Lucky Me! Pancit Canton Original",
    slug: "lucky-me-pancit-canton",
    brand: "Lucky Me",
    unit: "pack",
    unitSize: "65g",
    price: 14,
    srp: 18,
    sku: "LM-PC-ORI",
    minOrderQty: 12,
    isActive: true,
    isFeatured: true,
    stock: 960,
    lowStockThreshold: 96,
    createdAt: "2024-01-01T00:00:00Z",
    description: "Lucky Me Pancit Canton Original flavor. 12 packs per box.",
    imageUrl: "https://images.unsplash.com/photo-1569718212165-3a8278d5f624?w=400&q=80&auto=format&fit=crop",
  },
  {
    id: "prod-10",
    categoryId: "cat-2",
    name: "Nissin Wafer Sticks Vanilla 50g",
    slug: "nissin-wafer-vanilla",
    brand: "Nissin",
    unit: "pack",
    unitSize: "50g",
    price: 18,
    srp: 22,
    sku: "NIS-WAF-VAN",
    minOrderQty: 12,
    isActive: true,
    isFeatured: false,
    stock: 0,
    lowStockThreshold: 24,
    createdAt: "2024-01-01T00:00:00Z",
    description: "Nissin wafer sticks, vanilla cream filling.",
    imageUrl: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&q=80&auto=format&fit=crop",
  },
  {
    id: "prod-15",
    categoryId: "cat-2",
    name: "Lucky Me! Chicken Mami 55g",
    slug: "lucky-me-chicken-mami",
    brand: "Lucky Me",
    unit: "pack",
    unitSize: "55g",
    price: 12,
    srp: 16,
    sku: "LM-CM-55",
    minOrderQty: 12,
    isActive: true,
    isFeatured: false,
    stock: 720,
    lowStockThreshold: 96,
    createdAt: "2024-01-01T00:00:00Z",
    description: "Lucky Me! Chicken Mami instant noodle soup, 55g pack.",
    imageUrl: "https://images.unsplash.com/photo-1585032226651-759b368d7246?w=400&q=80&auto=format&fit=crop",
  },
  {
    id: "prod-16",
    categoryId: "cat-2",
    name: "Quickchow Pancit Canton 100g",
    slug: "quickchow-pancit-canton-100g",
    brand: "Quickchow",
    unit: "pack",
    unitSize: "100g",
    price: 16,
    srp: 20,
    sku: "QC-PC-100",
    minOrderQty: 12,
    isActive: true,
    isFeatured: false,
    stock: 480,
    lowStockThreshold: 48,
    createdAt: "2024-01-01T00:00:00Z",
    description: "Quickchow Pancit Canton stir-fry noodles, 100g pack.",
    imageUrl: "https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=400&q=80&auto=format&fit=crop",
  },

  // ── Snacks & Chips (cat-3) ────────────────────────────────────────────────
  {
    id: "prod-3",
    categoryId: "cat-3",
    name: "Piattos Cheese 85g",
    slug: "piattos-cheese",
    brand: "Piattos",
    unit: "pack",
    unitSize: "85g",
    price: 38,
    srp: 45,
    sku: "PIT-CHE-85",
    minOrderQty: 10,
    isActive: true,
    isFeatured: false,
    stock: 240,
    lowStockThreshold: 30,
    createdAt: "2024-01-01T00:00:00Z",
    description: "Piattos potato crisps in cheese flavor.",
    imageUrl: "https://images.unsplash.com/photo-1566478989037-eec170784d0b?w=400&q=80&auto=format&fit=crop",
  },
  {
    id: "prod-17",
    categoryId: "cat-3",
    name: "Nova Country Cheddar 78g",
    slug: "nova-country-cheddar-78g",
    brand: "Nova",
    unit: "pack",
    unitSize: "78g",
    price: 35,
    srp: 42,
    sku: "NOV-CCD-78",
    minOrderQty: 12,
    isActive: true,
    isFeatured: false,
    stock: 312,
    lowStockThreshold: 36,
    createdAt: "2024-01-01T00:00:00Z",
    description: "Nova Country Cheddar corn snacks, 78g pack.",
    imageUrl: "https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?w=400&q=80&auto=format&fit=crop",
  },
  {
    id: "prod-18",
    categoryId: "cat-3",
    name: "Clover Chips Original 100g",
    slug: "clover-chips-original-100g",
    brand: "Clover",
    unit: "pack",
    unitSize: "100g",
    price: 28,
    srp: 35,
    sku: "CLV-CHI-100",
    minOrderQty: 12,
    isActive: true,
    isFeatured: false,
    stock: 264,
    lowStockThreshold: 36,
    createdAt: "2024-01-01T00:00:00Z",
    description: "Clover Chips original flavored snack, 100g pack.",
    imageUrl: "https://images.unsplash.com/photo-1600952841320-db92ec4047ca?w=400&q=80&auto=format&fit=crop",
  },
  {
    id: "prod-19",
    categoryId: "cat-3",
    name: "Chippy BBQ 100g",
    slug: "chippy-bbq-100g",
    brand: "Chippy",
    unit: "pack",
    unitSize: "100g",
    price: 26,
    srp: 32,
    sku: "CHP-BBQ-100",
    minOrderQty: 12,
    isActive: true,
    isFeatured: false,
    stock: 360,
    lowStockThreshold: 36,
    createdAt: "2024-01-01T00:00:00Z",
    description: "Chippy corn chips in BBQ flavor, 100g pack.",
    imageUrl: "https://images.unsplash.com/photo-1566478989037-eec170784d0b?w=400&q=80&auto=format&fit=crop",
  },
  {
    id: "prod-20",
    categoryId: "cat-3",
    name: "Boy Bawang Corn Bits 100g",
    slug: "boy-bawang-corn-bits-100g",
    brand: "Boy Bawang",
    unit: "pack",
    unitSize: "100g",
    price: 24,
    srp: 30,
    sku: "BB-CRN-100",
    minOrderQty: 12,
    isActive: true,
    isFeatured: false,
    stock: 420,
    lowStockThreshold: 48,
    createdAt: "2024-01-01T00:00:00Z",
    description: "Boy Bawang garlic-flavored corn bits, 100g pack.",
    imageUrl: "https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?w=400&q=80&auto=format&fit=crop",
  },
  {
    id: "prod-21",
    categoryId: "cat-3",
    name: "Ricoa Curls Cheese 68g",
    slug: "ricoa-curls-cheese-68g",
    brand: "Ricoa",
    unit: "pack",
    unitSize: "68g",
    price: 22,
    srp: 28,
    sku: "RCO-CRL-68",
    minOrderQty: 12,
    isActive: true,
    isFeatured: false,
    stock: 288,
    lowStockThreshold: 36,
    createdAt: "2024-01-01T00:00:00Z",
    description: "Ricoa Curls cheese-flavored corn puffs, 68g pack.",
    imageUrl: "https://images.unsplash.com/photo-1542435503-956c469947f6?w=400&q=80&auto=format&fit=crop",
  },

  // ── Canned Goods (cat-4) ──────────────────────────────────────────────────
  {
    id: "prod-4",
    categoryId: "cat-4",
    name: "555 Sardines in Tomato Sauce 155g",
    slug: "555-sardines-tomato",
    brand: "555",
    unit: "can",
    unitSize: "155g",
    price: 28,
    srp: 34,
    sku: "555-SAR-TOM",
    minOrderQty: 24,
    isActive: true,
    isFeatured: true,
    stock: 576,
    lowStockThreshold: 48,
    createdAt: "2024-01-01T00:00:00Z",
    description: "555 Sardines in tomato sauce. 24 cans per case.",
    imageUrl: "https://images.unsplash.com/photo-1615485500704-8e990f9900f7?w=400&q=80&auto=format&fit=crop",
  },
  {
    id: "prod-22",
    categoryId: "cat-4",
    name: "Mega Sardines Spicy 155g",
    slug: "mega-sardines-spicy-155g",
    brand: "Mega",
    unit: "can",
    unitSize: "155g",
    price: 24,
    srp: 30,
    sku: "MEG-SAR-SPI",
    minOrderQty: 24,
    isActive: true,
    isFeatured: false,
    stock: 432,
    lowStockThreshold: 48,
    createdAt: "2024-01-01T00:00:00Z",
    description: "Mega Sardines in spicy tomato sauce, 155g can.",
    imageUrl: "https://images.unsplash.com/photo-1584949602334-4e32a8d5ac46?w=400&q=80&auto=format&fit=crop",
  },
  {
    id: "prod-23",
    categoryId: "cat-4",
    name: "Argentina Corned Beef 260g",
    slug: "argentina-corned-beef-260g",
    brand: "Argentina",
    unit: "can",
    unitSize: "260g",
    price: 58,
    srp: 72,
    sku: "ARG-CB-260",
    minOrderQty: 24,
    isActive: true,
    isFeatured: true,
    stock: 288,
    lowStockThreshold: 48,
    createdAt: "2024-01-01T00:00:00Z",
    description: "Argentina Corned Beef, 260g can. Classic sari-sari staple.",
    imageUrl: "https://images.unsplash.com/photo-1608198093002-ad4e005484ec?w=400&q=80&auto=format&fit=crop",
  },
  {
    id: "prod-24",
    categoryId: "cat-4",
    name: "Century Tuna Flakes in Oil 180g",
    slug: "century-tuna-flakes-oil-180g",
    brand: "Century Tuna",
    unit: "can",
    unitSize: "180g",
    price: 46,
    srp: 58,
    sku: "CTF-OIL-180",
    minOrderQty: 24,
    isActive: true,
    isFeatured: false,
    stock: 360,
    lowStockThreshold: 48,
    createdAt: "2024-01-01T00:00:00Z",
    description: "Century Tuna flakes in oil, 180g can.",
    imageUrl: "https://images.unsplash.com/photo-1559622214-f8a9850965bb?w=400&q=80&auto=format&fit=crop",
  },

  // ── Condiments & Sauces (cat-5) ───────────────────────────────────────────
  {
    id: "prod-7",
    categoryId: "cat-5",
    name: "Silver Swan Soy Sauce 1L",
    slug: "silver-swan-soy-sauce-1l",
    brand: "Silver Swan",
    unit: "bottle",
    unitSize: "1L",
    price: 62,
    srp: 75,
    sku: "SS-SOY-1L",
    minOrderQty: 12,
    isActive: true,
    isFeatured: false,
    stock: 144,
    lowStockThreshold: 24,
    createdAt: "2024-01-01T00:00:00Z",
    description: "Silver Swan regular soy sauce, 1 liter bottle.",
    imageUrl: "https://images.unsplash.com/photo-1472476443507-c7a5948772fc?w=400&q=80&auto=format&fit=crop",
  },
  {
    id: "prod-25",
    categoryId: "cat-5",
    name: "Datu Puti Sukang Maasim 1L",
    slug: "datu-puti-sukang-maasim-1l",
    brand: "Datu Puti",
    unit: "bottle",
    unitSize: "1L",
    price: 45,
    srp: 55,
    sku: "DP-SUK-1L",
    minOrderQty: 12,
    isActive: true,
    isFeatured: false,
    stock: 216,
    lowStockThreshold: 24,
    createdAt: "2024-01-01T00:00:00Z",
    description: "Datu Puti Sukang Maasim cane vinegar, 1 liter bottle.",
    imageUrl: "https://images.unsplash.com/photo-1614041984404-40d462f1a1f7?w=400&q=80&auto=format&fit=crop",
  },
  {
    id: "prod-26",
    categoryId: "cat-5",
    name: "UFC Banana Ketchup 320g",
    slug: "ufc-banana-ketchup-320g",
    brand: "UFC",
    unit: "bottle",
    unitSize: "320g",
    price: 48,
    srp: 60,
    sku: "UFC-BKT-320",
    minOrderQty: 12,
    isActive: true,
    isFeatured: false,
    stock: 180,
    lowStockThreshold: 24,
    createdAt: "2024-01-01T00:00:00Z",
    description: "UFC Banana Ketchup original sweet style, 320g bottle.",
    imageUrl: "https://images.unsplash.com/photo-1503764654157-72d979d9af2f?w=400&q=80&auto=format&fit=crop",
  },
  {
    id: "prod-27",
    categoryId: "cat-5",
    name: "Minola Coconut Oil 1L",
    slug: "minola-coconut-oil-1l",
    brand: "Minola",
    unit: "bottle",
    unitSize: "1L",
    price: 72,
    srp: 90,
    sku: "MIN-CO-1L",
    minOrderQty: 12,
    isActive: true,
    isFeatured: false,
    stock: 120,
    lowStockThreshold: 24,
    createdAt: "2024-01-01T00:00:00Z",
    description: "Minola refined coconut cooking oil, 1 liter bottle.",
    imageUrl: "https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=400&q=80&auto=format&fit=crop",
  },

  // ── Personal Care (cat-6) ─────────────────────────────────────────────────
  {
    id: "prod-6",
    categoryId: "cat-6",
    name: "Safeguard Classic Bar 60g",
    slug: "safeguard-classic-60g",
    brand: "Safeguard",
    unit: "bar",
    unitSize: "60g",
    price: 22,
    srp: 27,
    sku: "SFG-CLA-60",
    minOrderQty: 24,
    isActive: true,
    isFeatured: false,
    stock: 480,
    lowStockThreshold: 48,
    createdAt: "2024-01-01T00:00:00Z",
    description: "Safeguard antibacterial bar soap, classic white.",
    imageUrl: "https://images.unsplash.com/photo-1608248543803-ba4f8c70ae0b?w=400&q=80&auto=format&fit=crop",
  },
  {
    id: "prod-28",
    categoryId: "cat-6",
    name: "Head & Shoulders Classic 100ml",
    slug: "head-shoulders-classic-100ml",
    brand: "Head & Shoulders",
    unit: "bottle",
    unitSize: "100ml",
    price: 55,
    srp: 68,
    sku: "HS-CLS-100",
    minOrderQty: 12,
    isActive: true,
    isFeatured: false,
    stock: 240,
    lowStockThreshold: 36,
    createdAt: "2024-01-01T00:00:00Z",
    description: "Head & Shoulders Classic Clean anti-dandruff shampoo, 100ml bottle.",
    imageUrl: "https://images.unsplash.com/photo-1585231929568-9b0f2871c48e?w=400&q=80&auto=format&fit=crop",
  },
  {
    id: "prod-29",
    categoryId: "cat-6",
    name: "Palmolive Naturals 100ml",
    slug: "palmolive-naturals-100ml",
    brand: "Palmolive",
    unit: "bottle",
    unitSize: "100ml",
    price: 48,
    srp: 60,
    sku: "PLM-NAT-100",
    minOrderQty: 12,
    isActive: true,
    isFeatured: false,
    stock: 288,
    lowStockThreshold: 36,
    createdAt: "2024-01-01T00:00:00Z",
    description: "Palmolive Naturals shampoo with milk and honey, 100ml bottle.",
    imageUrl: "https://images.unsplash.com/photo-1543363950-b1e4e17dc7c5?w=400&q=80&auto=format&fit=crop",
  },
  {
    id: "prod-30",
    categoryId: "cat-6",
    name: "Colgate Fluoride Toothpaste 75ml",
    slug: "colgate-fluoride-75ml",
    brand: "Colgate",
    unit: "tube",
    unitSize: "75ml",
    price: 45,
    srp: 55,
    sku: "COL-FLU-75",
    minOrderQty: 12,
    isActive: true,
    isFeatured: false,
    stock: 360,
    lowStockThreshold: 48,
    createdAt: "2024-01-01T00:00:00Z",
    description: "Colgate Fluoride toothpaste cavity protection, 75ml tube.",
    imageUrl: "https://images.unsplash.com/photo-1559086648-f0bfcfed8db0?w=400&q=80&auto=format&fit=crop",
  },

  // ── Coffee & Milo (cat-7) ─────────────────────────────────────────────────
  {
    id: "prod-5",
    categoryId: "cat-7",
    name: "Nescafé 3-in-1 Original 20g x 10pcs",
    slug: "nescafe-3in1-original",
    brand: "Nescafé",
    unit: "box",
    unitSize: "20g x 10",
    price: 85,
    srp: 100,
    sku: "NES-3IN1-ORI",
    minOrderQty: 10,
    isActive: true,
    isFeatured: true,
    stock: 300,
    lowStockThreshold: 50,
    createdAt: "2024-01-01T00:00:00Z",
    description: "Nescafé 3-in-1 Original blend. 10 sachets per box.",
    imageUrl: "https://images.unsplash.com/photo-1461023058943-362d33763543?w=400&q=80&auto=format&fit=crop",
  },
  {
    id: "prod-31",
    categoryId: "cat-7",
    name: "Kopiko 3-in-1 Coffee 25g x 10",
    slug: "kopiko-3in1-coffee-25g-x10",
    brand: "Kopiko",
    unit: "box",
    unitSize: "25g x 10",
    price: 95,
    srp: 115,
    sku: "KPK-3IN1-25",
    minOrderQty: 12,
    isActive: true,
    isFeatured: false,
    stock: 240,
    lowStockThreshold: 36,
    createdAt: "2024-01-01T00:00:00Z",
    description: "Kopiko 3-in-1 instant coffee mix, 25g sachets, 10 per box.",
    imageUrl: "https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=400&q=80&auto=format&fit=crop",
  },

  // ── Laundry & Cleaning (cat-8) ────────────────────────────────────────────
  {
    id: "prod-8",
    categoryId: "cat-8",
    name: "Surf Powder Detergent 80g x 6",
    slug: "surf-powder-80g",
    brand: "Surf",
    unit: "pack",
    unitSize: "80g",
    price: 48,
    srp: 58,
    sku: "SURF-PWD-80",
    minOrderQty: 12,
    isActive: true,
    isFeatured: false,
    stock: 360,
    lowStockThreshold: 60,
    createdAt: "2024-01-01T00:00:00Z",
    description: "Surf powder detergent in 80g sachets. 6 sachets per pack.",
    imageUrl: "https://images.unsplash.com/photo-1582735689369-4fe89db7114c?w=400&q=80&auto=format&fit=crop",
  },
  {
    id: "prod-32",
    categoryId: "cat-8",
    name: "Ariel Powder Detergent 57g x 6",
    slug: "ariel-powder-57g-x6",
    brand: "Ariel",
    unit: "pack",
    unitSize: "57g x 6",
    price: 52,
    srp: 64,
    sku: "ARI-PWD-57",
    minOrderQty: 12,
    isActive: true,
    isFeatured: false,
    stock: 312,
    lowStockThreshold: 48,
    createdAt: "2024-01-01T00:00:00Z",
    description: "Ariel powder detergent with Odor Eliminator, 57g sachets, 6 per pack.",
    imageUrl: "https://images.unsplash.com/photo-1610557892470-55d9e80c0bce?w=400&q=80&auto=format&fit=crop",
  },
  {
    id: "prod-33",
    categoryId: "cat-8",
    name: "Downy Fabric Conditioner 27ml x 6",
    slug: "downy-fabric-conditioner-27ml-x6",
    brand: "Downy",
    unit: "pack",
    unitSize: "27ml x 6",
    price: 45,
    srp: 55,
    sku: "DWN-FAB-27",
    minOrderQty: 12,
    isActive: true,
    isFeatured: false,
    stock: 360,
    lowStockThreshold: 48,
    createdAt: "2024-01-01T00:00:00Z",
    description: "Downy Sunrise Fresh fabric conditioner, 27ml sachets, 6 per pack.",
    imageUrl: "https://images.unsplash.com/photo-1631729371254-42c2892f0e6e?w=400&q=80&auto=format&fit=crop",
  },
];

export const MOCK_ORDERS: Order[] = [
  {
    id: "ord-001",
    orderNumber: "KSS-2025-00142",
    storeId: "store-1",
    userId: "user-1",
    status: "out_for_delivery",
    paymentStatus: "paid",
    paymentMethod: "gcash",
    subtotal: 1420,
    deliveryFee: 80,
    total: 1500,
    deliveryAddress: "123 Rizal St., Barangay 5, Caloocan City",
    notes: "Please call before arriving",
    items: [
      { id: "oi-1", orderId: "ord-001", productId: "prod-1", quantity: 24, unitPrice: 28, totalPrice: 672, status: "picked" as const, fulfilledQty: 24 },
      { id: "oi-2", orderId: "ord-001", productId: "prod-2", quantity: 48, unitPrice: 14, totalPrice: 672, status: "picked" as const, fulfilledQty: 48 },
      { id: "oi-3", orderId: "ord-001", productId: "prod-5", quantity: 10, unitPrice: 85, totalPrice: 850, status: "pending" as const },
    ],
    fulfillmentEvents: [],
    createdAt: "2025-01-20T08:30:00Z",
    updatedAt: "2025-01-20T14:00:00Z",
  },
  {
    id: "ord-002",
    orderNumber: "KSS-2025-00141",
    storeId: "store-1",
    userId: "user-1",
    status: "delivered",
    paymentStatus: "paid",
    paymentMethod: "cod",
    subtotal: 2240,
    deliveryFee: 80,
    total: 2320,
    deliveryAddress: "123 Rizal St., Barangay 5, Caloocan City",
    items: [
      { id: "oi-4", orderId: "ord-002", productId: "prod-4", quantity: 48, unitPrice: 28, totalPrice: 1344, status: "picked" as const, fulfilledQty: 48 },
      { id: "oi-5", orderId: "ord-002", productId: "prod-7", quantity: 12, unitPrice: 62, totalPrice: 744, status: "picked" as const, fulfilledQty: 12 },
      { id: "oi-6", orderId: "ord-002", productId: "prod-6", quantity: 24, unitPrice: 22, totalPrice: 528, status: "picked" as const, fulfilledQty: 24 },
    ],
    fulfillmentEvents: [],
    createdAt: "2025-01-17T09:00:00Z",
    updatedAt: "2025-01-18T16:30:00Z",
  },
  {
    id: "ord-003",
    orderNumber: "KSS-2025-00138",
    storeId: "store-1",
    userId: "user-1",
    status: "delivered",
    paymentStatus: "paid",
    paymentMethod: "gcash",
    subtotal: 1890,
    deliveryFee: 80,
    total: 1970,
    deliveryAddress: "123 Rizal St., Barangay 5, Caloocan City",
    items: [],
    fulfillmentEvents: [],
    createdAt: "2025-01-12T10:00:00Z",
    updatedAt: "2025-01-13T15:00:00Z",
  },
];

export const MOCK_NOTIFICATIONS: Notification[] = [
  {
    id: "notif-1",
    userId: "user-1",
    type: "order_out_for_delivery",
    title: "Order on the way!",
    message: "Your order #KSS-2025-00142 is out for delivery. Expected by 5PM today.",
    isRead: false,
    orderId: "ord-001",
    createdAt: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
  },
  {
    id: "notif-2",
    userId: "user-1",
    type: "order_confirmed",
    title: "Order confirmed",
    message: "Your order #KSS-2025-00142 has been confirmed and is being prepared.",
    isRead: false,
    orderId: "ord-001",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 3).toISOString(),
  },
  {
    id: "notif-3",
    userId: "user-1",
    type: "subscription_expiring",
    title: "Subscription renews in 7 days",
    message: "Your Ka Sari-Sari subscription renews on Feb 1. Make sure your payment method is up to date.",
    isRead: true,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
  },
];

export const ADMIN_STATS: AdminStats = {
  totalOrders: 1_847,
  ordersToday: 38,
  revenueToday: 58_420,
  revenueMonth: 1_248_600,
  activeRetailers: 312,
  newRetailersMonth: 24,
  pendingOrders: 14,
  lowStockItems: 6,
};

export const ADMIN_RECENT_ORDERS: Order[] = [
  { id: "ord-a1", orderNumber: "KSS-2025-00145", storeId: "s1", userId: "u1", status: "pending", paymentStatus: "paid", paymentMethod: "gcash", subtotal: 1840, deliveryFee: 80, total: 1920, deliveryAddress: "Quezon City", items: [], fulfillmentEvents: [], createdAt: new Date(Date.now() - 1000 * 60 * 15).toISOString(), updatedAt: new Date().toISOString() },
  { id: "ord-a2", orderNumber: "KSS-2025-00144", storeId: "s2", userId: "u2", status: "picking", paymentStatus: "paid", paymentMethod: "gcash", subtotal: 3200, deliveryFee: 80, total: 3280, deliveryAddress: "Marikina City", items: [], fulfillmentEvents: [], createdAt: new Date(Date.now() - 1000 * 60 * 45).toISOString(), updatedAt: new Date().toISOString() },
  { id: "ord-a3", orderNumber: "KSS-2025-00143", storeId: "s3", userId: "u3", status: "packed", paymentStatus: "paid", paymentMethod: "cod", subtotal: 980, deliveryFee: 80, total: 1060, deliveryAddress: "Caloocan City", items: [], fulfillmentEvents: [], createdAt: new Date(Date.now() - 1000 * 60 * 90).toISOString(), updatedAt: new Date().toISOString() },
  { id: "ord-a4", orderNumber: "KSS-2025-00142", storeId: "s4", userId: "u4", status: "out_for_delivery", paymentStatus: "paid", paymentMethod: "gcash", subtotal: 1420, deliveryFee: 80, total: 1500, deliveryAddress: "Caloocan City", items: [], fulfillmentEvents: [], createdAt: new Date(Date.now() - 1000 * 60 * 120).toISOString(), updatedAt: new Date().toISOString() },
  { id: "ord-a5", orderNumber: "KSS-2025-00141", storeId: "s5", userId: "u5", status: "delivered", paymentStatus: "paid", paymentMethod: "gcash", subtotal: 2240, deliveryFee: 80, total: 2320, deliveryAddress: "Pasig City", items: [], fulfillmentEvents: [], createdAt: new Date(Date.now() - 1000 * 60 * 180).toISOString(), updatedAt: new Date().toISOString() },
];

// ─── Suppliers ────────────────────────────────────────────────────────────────

export const SUPPLIERS: Supplier[] = [
  {
    id: "sup-1",
    name: "PhilBev Distribution Inc.",
    contactName: "Roberto Aquino",
    phone: "+63 2 8888 1234",
    email: "roberto@philbev.com",
    address: "123 Industrial Ave, Valenzuela City",
    city: "Valenzuela City",
    status: "active",
    paymentTerms: "30 days NET",
    leadTimeDays: 3,
    totalPurchases: 2_450_000,
    lastOrderDate: "2025-01-15T00:00:00Z",
    categories: ["Beverages", "Coffee & Milo"],
    createdAt: "2023-06-01T00:00:00Z",
  },
  {
    id: "sup-2",
    name: "Lucky Me Foods Corp",
    contactName: "Sandra Villanueva",
    phone: "+63 2 8777 9900",
    email: "orders@luckyme.com",
    address: "45 Commerce Blvd, Taguig City",
    city: "Taguig City",
    status: "active",
    paymentTerms: "COD",
    leadTimeDays: 2,
    totalPurchases: 1_820_000,
    lastOrderDate: "2025-01-18T00:00:00Z",
    categories: ["Instant Noodles", "Snacks & Chips"],
    createdAt: "2023-08-15T00:00:00Z",
  },
  {
    id: "sup-3",
    name: "Del Monte Philippines",
    contactName: "Carlos Mendoza",
    phone: "+63 2 8999 5678",
    email: "c.mendoza@delmonte.ph",
    address: "789 Bulacan Industrial Complex, Bulacan",
    city: "Malolos City",
    status: "active",
    paymentTerms: "15 days NET",
    leadTimeDays: 4,
    totalPurchases: 980_000,
    lastOrderDate: "2025-01-10T00:00:00Z",
    categories: ["Canned Goods", "Condiments & Sauces"],
    createdAt: "2023-11-20T00:00:00Z",
  },
  {
    id: "sup-4",
    name: "Procter & Gamble Philippines",
    contactName: "Maricel Santos",
    phone: "+63 2 8555 4321",
    email: "ph.orders@pg.com",
    address: "One Corporate Center, Ortigas, Pasig City",
    city: "Pasig City",
    status: "active",
    paymentTerms: "45 days NET",
    leadTimeDays: 5,
    totalPurchases: 3_200_000,
    lastOrderDate: "2025-01-20T00:00:00Z",
    categories: ["Personal Care", "Laundry & Cleaning"],
    createdAt: "2023-04-01T00:00:00Z",
  },
  {
    id: "sup-5",
    name: "Mega Global Corp",
    contactName: "Jaime Reyes",
    phone: "+63 2 8333 7788",
    email: "jaime@megaglobal.ph",
    address: "560 EDSA, Balintawak, Quezon City",
    city: "Quezon City",
    status: "active",
    paymentTerms: "30 days NET",
    leadTimeDays: 3,
    totalPurchases: 755_000,
    lastOrderDate: "2025-01-12T00:00:00Z",
    categories: ["Canned Goods"],
    createdAt: "2024-01-10T00:00:00Z",
  },
];

// ─── Drivers ──────────────────────────────────────────────────────────────────

export const DRIVERS: Driver[] = [
  {
    id: "drv-1",
    name: "Rodrigo Delos Santos",
    phone: "+63 917 111 2222",
    licenseNumber: "D10-23-456789",
    vehicleType: "van",
    vehiclePlate: "AAA 1234",
    status: "on_route",
    rating: 4.9,
    deliveriesTotal: 1247,
    deliveriesToday: 8,
    currentRouteId: "route-1",
    avatarInitials: "RD",
    createdAt: "2023-06-15T00:00:00Z",
  },
  {
    id: "drv-2",
    name: "Benjamin Cruz",
    phone: "+63 918 222 3333",
    licenseNumber: "D10-22-112233",
    vehicleType: "van",
    vehiclePlate: "BBB 5678",
    status: "on_route",
    rating: 4.7,
    deliveriesTotal: 892,
    deliveriesToday: 5,
    currentRouteId: "route-2",
    avatarInitials: "BC",
    createdAt: "2023-09-01T00:00:00Z",
  },
  {
    id: "drv-3",
    name: "Antonio Lim",
    phone: "+63 919 333 4444",
    licenseNumber: "D10-21-998877",
    vehicleType: "tricycle",
    vehiclePlate: "CC 9012",
    status: "active",
    rating: 4.8,
    deliveriesTotal: 2105,
    deliveriesToday: 0,
    avatarInitials: "AL",
    createdAt: "2022-03-20T00:00:00Z",
  },
  {
    id: "drv-4",
    name: "Mark Villanueva",
    phone: "+63 920 444 5555",
    licenseNumber: "D10-23-667788",
    vehicleType: "motorcycle",
    vehiclePlate: "DDD 3456",
    status: "off_duty",
    rating: 4.6,
    deliveriesTotal: 456,
    deliveriesToday: 0,
    avatarInitials: "MV",
    createdAt: "2024-01-05T00:00:00Z",
  },
  {
    id: "drv-5",
    name: "Jose Fernandez",
    phone: "+63 921 555 6666",
    licenseNumber: "D10-20-334455",
    vehicleType: "van",
    vehiclePlate: "EEE 7890",
    status: "active",
    rating: 4.95,
    deliveriesTotal: 3420,
    deliveriesToday: 0,
    avatarInitials: "JF",
    createdAt: "2021-11-10T00:00:00Z",
  },
];

// ─── Routes ───────────────────────────────────────────────────────────────────

export const ROUTES: Route[] = [
  {
    id: "route-1",
    name: "Caloocan North",
    driverId: "drv-1",
    status: "active",
    stops: 12,
    completedStops: 7,
    distance: "34 km",
    estimatedDuration: "4 hrs",
    orderIds: ["ord-a1", "ord-a2", "ord-a4"],
    startedAt: new Date(Date.now() - 1000 * 60 * 120).toISOString(),
    createdAt: new Date(Date.now() - 1000 * 60 * 180).toISOString(),
  },
  {
    id: "route-2",
    name: "Marikina - Pasig",
    driverId: "drv-2",
    status: "active",
    stops: 9,
    completedStops: 4,
    distance: "28 km",
    estimatedDuration: "3.5 hrs",
    orderIds: ["ord-a3", "ord-a5"],
    startedAt: new Date(Date.now() - 1000 * 60 * 90).toISOString(),
    createdAt: new Date(Date.now() - 1000 * 60 * 150).toISOString(),
  },
  {
    id: "route-3",
    name: "Quezon City South",
    status: "planned",
    stops: 15,
    completedStops: 0,
    distance: "41 km",
    estimatedDuration: "5 hrs",
    orderIds: [],
    createdAt: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
  },
];

// ─── Purchase Orders ──────────────────────────────────────────────────────────

export const PURCHASE_ORDERS: PurchaseOrder[] = [
  {
    id: "po-001",
    poNumber: "PO-2025-0089",
    supplierId: "sup-1",
    status: "confirmed",
    items: [
      { id: "poi-1", purchaseOrderId: "po-001", productId: "prod-1", productName: "Coca-Cola Regular 330ml", sku: "CC-330-REG", orderedQty: 960, receivedQty: 0, unitCost: 22, totalCost: 21120 },
      { id: "poi-2", purchaseOrderId: "po-001", productId: "prod-9", productName: "Wilkins Pure Distilled Water 500ml", sku: "WLK-500-PUR", orderedQty: 480, receivedQty: 0, unitCost: 9, totalCost: 4320 },
    ],
    subtotal: 25440,
    total: 25440,
    expectedDate: new Date(Date.now() + 1000 * 60 * 60 * 48).toISOString(),
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 60 * 12).toISOString(),
  },
  {
    id: "po-002",
    poNumber: "PO-2025-0088",
    supplierId: "sup-2",
    status: "received",
    items: [
      { id: "poi-3", purchaseOrderId: "po-002", productId: "prod-2", productName: "Lucky Me! Pancit Canton Original", sku: "LM-PC-ORI", orderedQty: 480, receivedQty: 480, unitCost: 10, totalCost: 4800 },
    ],
    subtotal: 4800,
    total: 4800,
    expectedDate: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
    receivedDate: new Date(Date.now() - 1000 * 60 * 60 * 12).toISOString(),
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 72).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 60 * 12).toISOString(),
  },
  {
    id: "po-003",
    poNumber: "PO-2025-0087",
    supplierId: "sup-4",
    status: "sent",
    items: [
      { id: "poi-4", purchaseOrderId: "po-003", productId: "prod-6", productName: "Safeguard Classic Bar 60g", sku: "SFG-CLA-60", orderedQty: 480, receivedQty: 0, unitCost: 17, totalCost: 8160 },
      { id: "poi-5", purchaseOrderId: "po-003", productId: "prod-8", productName: "Surf Powder Detergent 80g x 6", sku: "SURF-PWD-80", orderedQty: 240, receivedQty: 0, unitCost: 38, totalCost: 9120 },
    ],
    subtotal: 17280,
    total: 17280,
    expectedDate: new Date(Date.now() + 1000 * 60 * 60 * 72).toISOString(),
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 48).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 60 * 48).toISOString(),
  },
];

// ─── Promotions ───────────────────────────────────────────────────────────────

export const PROMOTIONS: Promotion[] = [
  {
    id: "promo-1",
    title: "Flash Sale: Beverages",
    description: "Get 20% off all beverage products. Stock up for the week!",
    discountType: "percentage",
    discountValue: 20,
    minimumOrder: 500,
    categoryIds: ["cat-1"],
    startDate: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(),
    endDate: new Date(Date.now() + 1000 * 60 * 60 * 22).toISOString(),
    status: "active",
    usageCount: 47,
    maxUsage: 100,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
  },
  {
    id: "promo-2",
    title: "Bundle Deal: Snacks Bonanza",
    description: "Buy 100 packs of any chips, get 10% off your entire order.",
    discountType: "percentage",
    discountValue: 10,
    minimumOrder: 1000,
    categoryIds: ["cat-3"],
    startDate: new Date(Date.now() - 1000 * 60 * 60 * 48).toISOString(),
    endDate: new Date(Date.now() + 1000 * 60 * 60 * 48).toISOString(),
    status: "active",
    usageCount: 23,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 72).toISOString(),
  },
  {
    id: "promo-3",
    title: "Free Delivery Weekend",
    description: "Free delivery on all orders above PHP 2,000 this weekend.",
    discountType: "fixed",
    discountValue: 80,
    minimumOrder: 2000,
    startDate: new Date(Date.now() + 1000 * 60 * 60 * 24).toISOString(),
    endDate: new Date(Date.now() + 1000 * 60 * 60 * 72).toISOString(),
    status: "scheduled",
    usageCount: 0,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 12).toISOString(),
  },
  {
    id: "promo-4",
    title: "New Year Promo",
    description: "PHP 100 off orders above PHP 2,500.",
    discountType: "fixed",
    discountValue: 100,
    minimumOrder: 2500,
    startDate: "2025-01-01T00:00:00Z",
    endDate: "2025-01-15T23:59:59Z",
    status: "ended",
    usageCount: 156,
    createdAt: "2024-12-28T00:00:00Z",
  },
];

// ─── Pick Lists ───────────────────────────────────────────────────────────────

export const PICK_LISTS: PickList[] = [
  {
    id: "pl-001",
    orderId: "ord-a1",
    orderNumber: "KSS-2025-00145",
    status: "in_progress",
    assignedTo: "Warehouse Staff A",
    items: [
      { id: "pli-1", productId: "prod-1", productName: "Coca-Cola Regular 330ml", sku: "CC-330-REG", quantity: 24, pickedQty: 24, bin: "A1-S3-B2", status: "picked" },
      { id: "pli-2", productId: "prod-5", productName: "Nescafe 3-in-1 Original", sku: "NES-3IN1-ORI", quantity: 10, pickedQty: 5, bin: "B2-S1-B4", status: "partial" },
      { id: "pli-3", productId: "prod-4", productName: "555 Sardines in Tomato Sauce", sku: "555-SAR-TOM", quantity: 24, pickedQty: 0, bin: "C3-S2-B1", status: "pending" },
    ],
    createdAt: new Date(Date.now() - 1000 * 60 * 90).toISOString(),
  },
  {
    id: "pl-002",
    orderId: "ord-a2",
    orderNumber: "KSS-2025-00144",
    status: "open",
    items: [
      { id: "pli-4", productId: "prod-2", productName: "Lucky Me! Pancit Canton Original", sku: "LM-PC-ORI", quantity: 48, pickedQty: 0, bin: "A2-S4-B3", status: "pending" },
      { id: "pli-5", productId: "prod-6", productName: "Safeguard Classic Bar 60g", sku: "SFG-CLA-60", quantity: 48, pickedQty: 0, bin: "D1-S2-B5", status: "pending" },
    ],
    createdAt: new Date(Date.now() - 1000 * 60 * 45).toISOString(),
  },
  {
    id: "pl-003",
    orderId: "ord-a3",
    orderNumber: "KSS-2025-00143",
    status: "completed",
    assignedTo: "Warehouse Staff B",
    items: [
      { id: "pli-6", productId: "prod-7", productName: "Silver Swan Soy Sauce 1L", sku: "SS-SOY-1L", quantity: 12, pickedQty: 12, bin: "C1-S3-B2", status: "picked" },
      { id: "pli-7", productId: "prod-8", productName: "Surf Powder Detergent 80g x 6", sku: "SURF-PWD-80", quantity: 12, pickedQty: 12, bin: "D2-S1-B1", status: "picked" },
    ],
    createdAt: new Date(Date.now() - 1000 * 60 * 180).toISOString(),
    completedAt: new Date(Date.now() - 1000 * 60 * 60).toISOString(),
  },
];

// ─── Goods Receipts ───────────────────────────────────────────────────────────

export const GOODS_RECEIPTS: GoodsReceipt[] = [
  {
    id: "gr-001",
    purchaseOrderId: "po-001",
    poNumber: "PO-2025-0089",
    supplierName: "PhilBev Distribution Inc.",
    items: [
      { productName: "Coca-Cola Regular 330ml", sku: "CC-330-REG", expectedQty: 960, receivedQty: 0 },
      { productName: "Wilkins Pure Distilled Water 500ml", sku: "WLK-500-PUR", expectedQty: 480, receivedQty: 0 },
    ],
    status: "pending",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
  },
];
