import type { Category, Product, Order, User, Notification, AdminStats, Supplier, Driver, Route, PurchaseOrder, Promotion, PickList, GoodsReceipt } from "@/types";

export const CATEGORIES: Category[] = [
  { id: "cat-01", name: "Coffee & Creamer", slug: "coffee-creamer", productCount: 5, isActive: true, sortOrder: 1, description: "3-in-1 coffee, black coffee, creamers — Nescafé, Great Taste, Kopiko" },
  { id: "cat-02", name: "Instant Noodles", slug: "instant-noodles", productCount: 5, isActive: true, sortOrder: 2, description: "Pancit canton, mami, cup noodles — Lucky Me!, Nissin, Payless" },
  { id: "cat-03", name: "Biscuits & Snacks", slug: "biscuits-snacks", productCount: 6, isActive: true, sortOrder: 3, description: "Crackers, chips, cornick — SkyFlakes, Piattos, Boy Bawang, Oishi" },
  { id: "cat-04", name: "Candies & Chocolates", slug: "candies", productCount: 4, isActive: true, sortOrder: 4, description: "Chocolates, candy — Cloud 9, Choc Nut, Kopiko, Mentos" },
  { id: "cat-05", name: "Canned Goods", slug: "canned-goods", productCount: 5, isActive: true, sortOrder: 5, description: "Sardines, tuna, corned beef — 555, Century Tuna, Argentina" },
  { id: "cat-06", name: "Beverages", slug: "beverages", productCount: 6, isActive: true, sortOrder: 6, description: "Softdrinks, water, energy drinks — Coca-Cola, Sprite, Summit, Gatorade" },
  { id: "cat-07", name: "Powdered Drinks", slug: "powdered-drinks", productCount: 4, isActive: true, sortOrder: 7, description: "Milo, Tang, Ovaltine — instant powdered beverages" },
  { id: "cat-08", name: "Milk", slug: "milk", productCount: 4, isActive: true, sortOrder: 8, description: "Powdered, evaporated, condensed — Bear Brand, Alaska, Nido, Carnation" },
  { id: "cat-09", name: "Condiments & Sauces", slug: "condiments", productCount: 5, isActive: true, sortOrder: 9, description: "Soy sauce, vinegar, ketchup, seasonings — Silver Swan, Datu Puti, Knorr" },
  { id: "cat-10", name: "Cooking Essentials", slug: "cooking", productCount: 4, isActive: true, sortOrder: 10, description: "Oil, sugar, salt, flour — Golden Fiesta, Maya" },
  { id: "cat-11", name: "Bread Spreads", slug: "bread-spreads", productCount: 3, isActive: true, sortOrder: 11, description: "Margarine, peanut butter, cheese — Star Margarine, Cheez Whiz, Eden" },
  { id: "cat-12", name: "Bread & Bakery", slug: "bread-bakery", productCount: 3, isActive: true, sortOrder: 12, description: "Sliced bread, pandesal, ensaymada — Gardenia, Monde" },
  { id: "cat-13", name: "Eggs", slug: "eggs", productCount: 3, isActive: true, sortOrder: 13, description: "Chicken eggs, salted eggs, balut" },
  { id: "cat-14", name: "Rice", slug: "rice", productCount: 4, isActive: true, sortOrder: 14, description: "Premium, well-milled, regular — Sinandomeng, Dinorado, Jasmine" },
  { id: "cat-15", name: "Frozen & Chilled", slug: "frozen-chilled", productCount: 4, isActive: true, sortOrder: 15, description: "Hotdogs, tocino, nuggets, ice cream — Purefoods, CDO, Selecta" },
  { id: "cat-16", name: "Personal Care", slug: "personal-care", productCount: 5, isActive: true, sortOrder: 16, description: "Soap, shampoo, toothpaste, deodorant — Safeguard, Colgate, Sunsilk" },
  { id: "cat-17", name: "Feminine Care", slug: "feminine-care", productCount: 3, isActive: true, sortOrder: 17, description: "Sanitary napkins, panty liners — Modess, Whisper, Charmee" },
  { id: "cat-18", name: "Laundry", slug: "laundry", productCount: 5, isActive: true, sortOrder: 18, description: "Detergent, fabric conditioner, laundry bar — Surf, Ariel, Tide, Downy" },
  { id: "cat-19", name: "Household Cleaning", slug: "household-cleaning", productCount: 4, isActive: true, sortOrder: 19, description: "Dishwashing, bleach, toilet cleaner — Joy, Zonrox, Domex, Axion" },
  { id: "cat-20", name: "Insecticides & Repellents", slug: "insecticides", productCount: 3, isActive: true, sortOrder: 20, description: "Mosquito coils, sprays, repellents — Baygon, Katol, OFF!" },
  { id: "cat-21", name: "Baby Products", slug: "baby-products", productCount: 4, isActive: true, sortOrder: 21, description: "Diapers, powder, cereal — Pampers, Huggies, Johnson's, Cerelac" },
  { id: "cat-22", name: "School & Office Supplies", slug: "school-supplies", productCount: 3, isActive: true, sortOrder: 22, description: "Notebooks, ballpens, pencils — Corona, Panda, Mongol" },
  { id: "cat-23", name: "OTC Health Products", slug: "health-products", productCount: 5, isActive: true, sortOrder: 23, description: "Paracetamol, vitamins, alcohol, cold meds — Biogesic, Enervon, Green Cross" },
  { id: "cat-24", name: "Batteries & Lighters", slug: "batteries-lighters", productCount: 3, isActive: true, sortOrder: 24, description: "Batteries, lighters, candles — Eveready, Energizer, Tokai" },
  { id: "cat-25", name: "Ice & Water", slug: "ice-water", productCount: 3, isActive: true, sortOrder: 25, description: "Tube ice, purified water, water refill — Wilkins, Nature's Spring" },
  { id: "cat-26", name: "E-Load & Prepaid", slug: "e-load", productCount: 4, isActive: true, sortOrder: 26, description: "Smart, Globe, DITO load — gaming credits, GCash, Maya cash-in" },
];

export const PRODUCTS: Product[] = [
  // ── Coffee & Creamer (cat-01) ────────────────────────────────────
  {
    id: "cof-001", categoryId: "cat-01",
    name: "Nescafe 3-in-1 Original Blend 20g x 10", slug: "nescafe-3in1-original", brand: "Nescafe",
    unit: "pack", unitSize: "20g x 10 sachets", price: 75, srp: 90, sku: "NES-3IN1-ORI",
    minOrderQty: 24, isActive: true, isFeatured: true, stock: 960, lowStockThreshold: 96,
    createdAt: "2024-01-01T00:00:00Z", description: "Nescafe 3-in-1 Original Blend, 20g sachets, pack of 10.",
    imageUrl: "https://picsum.photos/seed/nescafe-3in1-original/400/400",
  },
  {
    id: "cof-002", categoryId: "cat-01",
    name: "Great Taste White Coffee 20g x 10", slug: "great-taste-white-coffee", brand: "Great Taste",
    unit: "pack", unitSize: "20g x 10 sachets", price: 80, srp: 95, sku: "GT-WHT-10",
    minOrderQty: 24, isActive: true, isFeatured: false, stock: 480, lowStockThreshold: 48,
    createdAt: "2024-01-01T00:00:00Z", description: "Great Taste White 3-in-1 coffee mix, 20g x 10 sachets.",
    imageUrl: "https://picsum.photos/seed/great-taste-white-coffee/400/400",
  },
  {
    id: "cof-003", categoryId: "cat-01",
    name: "Kopiko 3-in-1 Coffee 25g x 10", slug: "kopiko-3in1-coffee", brand: "Kopiko",
    unit: "pack", unitSize: "25g x 10 sachets", price: 70, srp: 85, sku: "KOP-3IN1-10",
    minOrderQty: 24, isActive: true, isFeatured: false, stock: 720, lowStockThreshold: 72,
    createdAt: "2024-01-01T00:00:00Z", description: "Kopiko 3-in-1 coffee with caramel taste, 25g x 10 sachets.",
    imageUrl: "https://picsum.photos/seed/kopiko-3in1-coffee/400/400",
  },
  {
    id: "cof-004", categoryId: "cat-01",
    name: "Blend 45 Coffee 25g x 10", slug: "blend45-coffee", brand: "Blend 45",
    unit: "pack", unitSize: "25g x 10 sachets", price: 65, srp: 78, sku: "BL45-25-10",
    minOrderQty: 24, isActive: true, isFeatured: false, stock: 480, lowStockThreshold: 48,
    createdAt: "2024-01-01T00:00:00Z", description: "Blend 45 instant coffee mix, 25g x 10 sachets.",
    imageUrl: "https://picsum.photos/seed/blend45-coffee/400/400",
  },
  {
    id: "cof-005", categoryId: "cat-01",
    name: "Coffee-Mate Non-Dairy Creamer 5g x 20", slug: "coffee-mate-creamer", brand: "Coffee-Mate",
    unit: "pack", unitSize: "5g x 20 sachets", price: 55, srp: 68, sku: "CFM-5G-20",
    minOrderQty: 24, isActive: true, isFeatured: false, stock: 360, lowStockThreshold: 36,
    createdAt: "2024-01-01T00:00:00Z", description: "Coffee-Mate non-dairy creamer, 5g x 20 sachets.",
    imageUrl: "https://picsum.photos/seed/coffee-mate-creamer/400/400",
  },
  // ── Instant Noodles (cat-02) ─────────────────────────────────────
  {
    id: "noo-001", categoryId: "cat-02",
    name: "Lucky Me Pancit Canton Original 65g", slug: "lucky-me-pancit-canton-original", brand: "Lucky Me",
    unit: "pack", unitSize: "65g", price: 14, srp: 18, sku: "LM-PC-ORI",
    minOrderQty: 48, isActive: true, isFeatured: true, stock: 1440, lowStockThreshold: 144,
    createdAt: "2024-01-01T00:00:00Z", description: "Lucky Me Pancit Canton Original Flavor, 65g.",
    imageUrl: "https://picsum.photos/seed/lucky-me-pancit-canton-original/400/400",
  },
  {
    id: "noo-002", categoryId: "cat-02",
    name: "Lucky Me Chicken Mami 55g", slug: "lucky-me-chicken-mami", brand: "Lucky Me",
    unit: "pack", unitSize: "55g", price: 13, srp: 16, sku: "LM-CHK-MAMI",
    minOrderQty: 48, isActive: true, isFeatured: false, stock: 960, lowStockThreshold: 96,
    createdAt: "2024-01-01T00:00:00Z", description: "Lucky Me Chicken Mami instant noodle soup, 55g.",
    imageUrl: "https://picsum.photos/seed/lucky-me-chicken-mami/400/400",
  },
  {
    id: "noo-003", categoryId: "cat-02",
    name: "Payless Pancit Canton 60g", slug: "payless-pancit-canton", brand: "Payless",
    unit: "pack", unitSize: "60g", price: 10, srp: 14, sku: "PAY-PC-60",
    minOrderQty: 48, isActive: true, isFeatured: false, stock: 1200, lowStockThreshold: 120,
    createdAt: "2024-01-01T00:00:00Z", description: "Payless Pancit Canton instant noodles, 60g.",
    imageUrl: "https://picsum.photos/seed/payless-pancit-canton/400/400",
  },
  {
    id: "noo-004", categoryId: "cat-02",
    name: "Nissin Cup Noodles Chicken 60g", slug: "nissin-cup-noodles-chicken", brand: "Nissin",
    unit: "cup", unitSize: "60g", price: 32, srp: 40, sku: "NIS-CUP-CHK",
    minOrderQty: 24, isActive: true, isFeatured: false, stock: 480, lowStockThreshold: 48,
    createdAt: "2024-01-01T00:00:00Z", description: "Nissin Cup Noodles Chicken flavor, 60g.",
    imageUrl: "https://picsum.photos/seed/nissin-cup-noodles-chicken/400/400",
  },
  {
    id: "noo-005", categoryId: "cat-02",
    name: "Mi Goreng Original Fried Noodles 80g", slug: "mi-goreng-original", brand: "Indomie",
    unit: "pack", unitSize: "80g", price: 25, srp: 32, sku: "MIG-ORI-80",
    minOrderQty: 24, isActive: true, isFeatured: false, stock: 360, lowStockThreshold: 36,
    createdAt: "2024-01-01T00:00:00Z", description: "Mi Goreng original Indonesian fried noodles, 80g.",
    imageUrl: "https://picsum.photos/seed/mi-goreng-original/400/400",
  },
  // ── Biscuits & Snacks (cat-03) ───────────────────────────────────
  {
    id: "bis-001", categoryId: "cat-03",
    name: "SkyFlakes Crackers 33g x 10", slug: "skyflakes-crackers-33g-x10", brand: "SkyFlakes",
    unit: "pack", unitSize: "33g x 10 packs", price: 65, srp: 80, sku: "SKF-33-10",
    minOrderQty: 24, isActive: true, isFeatured: true, stock: 720, lowStockThreshold: 72,
    createdAt: "2024-01-01T00:00:00Z", description: "SkyFlakes thin crispy wheat crackers, 33g x 10 packs per box.",
    imageUrl: "https://picsum.photos/seed/skyflakes-crackers-33g-x10/400/400",
  },
  {
    id: "bis-002", categoryId: "cat-03",
    name: "Fita Crackers Original 225g", slug: "fita-crackers-original", brand: "Fita",
    unit: "pack", unitSize: "225g", price: 48, srp: 58, sku: "FIT-ORI-225",
    minOrderQty: 24, isActive: true, isFeatured: false, stock: 480, lowStockThreshold: 48,
    createdAt: "2024-01-01T00:00:00Z", description: "Fita original crackers, 225g pack.",
    imageUrl: "https://picsum.photos/seed/fita-crackers-original/400/400",
  },
  {
    id: "bis-003", categoryId: "cat-03",
    name: "Cream-O Chocolate Sandwich Cookies 250g", slug: "cream-o-chocolate-250g", brand: "Cream-O",
    unit: "pack", unitSize: "250g", price: 55, srp: 68, sku: "CRO-CHO-250",
    minOrderQty: 24, isActive: true, isFeatured: false, stock: 360, lowStockThreshold: 36,
    createdAt: "2024-01-01T00:00:00Z", description: "Cream-O chocolate sandwich cookies, 250g.",
    imageUrl: "https://picsum.photos/seed/cream-o-chocolate-250g/400/400",
  },
  {
    id: "bis-004", categoryId: "cat-03",
    name: "Piattos Cheese Potato Crisps 85g", slug: "piattos-cheese-85g", brand: "Piattos",
    unit: "pack", unitSize: "85g", price: 28, srp: 35, sku: "PIA-CHE-85",
    minOrderQty: 24, isActive: true, isFeatured: true, stock: 960, lowStockThreshold: 96,
    createdAt: "2024-01-01T00:00:00Z", description: "Piattos cheese flavored potato crisps, 85g.",
    imageUrl: "https://picsum.photos/seed/piattos-cheese-85g/400/400",
  },
  {
    id: "bis-005", categoryId: "cat-03",
    name: "Boy Bawang Garlic Corn Bits 100g", slug: "boy-bawang-garlic-100g", brand: "Boy Bawang",
    unit: "pack", unitSize: "100g", price: 22, srp: 28, sku: "BB-GAR-100",
    minOrderQty: 24, isActive: true, isFeatured: false, stock: 720, lowStockThreshold: 72,
    createdAt: "2024-01-01T00:00:00Z", description: "Boy Bawang garlic flavored corn bits, 100g.",
    imageUrl: "https://picsum.photos/seed/boy-bawang-garlic-100g/400/400",
  },
  {
    id: "bis-006", categoryId: "cat-03",
    name: "Oishi Prawn Crackers Original 90g", slug: "oishi-prawn-crackers-90g", brand: "Oishi",
    unit: "pack", unitSize: "90g", price: 25, srp: 32, sku: "OIS-PRW-90",
    minOrderQty: 24, isActive: true, isFeatured: false, stock: 480, lowStockThreshold: 48,
    createdAt: "2024-01-01T00:00:00Z", description: "Oishi prawn crackers, original flavor, 90g.",
    imageUrl: "https://picsum.photos/seed/oishi-prawn-crackers-90g/400/400",
  },
  // ── Candies & Chocolates (cat-04) ────────────────────────────────
  {
    id: "cho-001", categoryId: "cat-04",
    name: "Cloud 9 Chocolate Bar 40g", slug: "cloud9-chocolate-bar-40g", brand: "Cloud 9",
    unit: "piece", unitSize: "40g", price: 22, srp: 28, sku: "CL9-CHO-40",
    minOrderQty: 24, isActive: true, isFeatured: true, stock: 720, lowStockThreshold: 72,
    createdAt: "2024-01-01T00:00:00Z", description: "Cloud 9 milk chocolate with caramel and wafer, 40g bar.",
    imageUrl: "https://picsum.photos/seed/cloud9-chocolate-bar-40g/400/400",
  },
  {
    id: "cho-002", categoryId: "cat-04",
    name: "Choc Nut Chocolate Peanut Candy 24pcs", slug: "choc-nut-24pcs", brand: "Choc Nut",
    unit: "box", unitSize: "24 pieces", price: 48, srp: 60, sku: "CHN-24PCS",
    minOrderQty: 12, isActive: true, isFeatured: false, stock: 480, lowStockThreshold: 48,
    createdAt: "2024-01-01T00:00:00Z", description: "Choc Nut chocolate peanut candy, box of 24 pieces.",
    imageUrl: "https://picsum.photos/seed/choc-nut-24pcs/400/400",
  },
  {
    id: "cho-003", categoryId: "cat-04",
    name: "Flat Tops Milk Chocolate 24pcs", slug: "flat-tops-milk-chocolate", brand: "Flat Tops",
    unit: "box", unitSize: "24 pieces", price: 45, srp: 56, sku: "FLT-MIL-24",
    minOrderQty: 12, isActive: true, isFeatured: false, stock: 480, lowStockThreshold: 48,
    createdAt: "2024-01-01T00:00:00Z", description: "Flat Tops milk chocolate, box of 24 pieces.",
    imageUrl: "https://picsum.photos/seed/flat-tops-milk-chocolate/400/400",
  },
  {
    id: "cho-004", categoryId: "cat-04",
    name: "Kopiko Coffee Candy 100g", slug: "kopiko-coffee-candy-100g", brand: "Kopiko",
    unit: "pack", unitSize: "100g", price: 38, srp: 48, sku: "KOP-CAN-100",
    minOrderQty: 24, isActive: true, isFeatured: false, stock: 600, lowStockThreshold: 60,
    createdAt: "2024-01-01T00:00:00Z", description: "Kopiko coffee hard candy, 100g resealable pack.",
    imageUrl: "https://picsum.photos/seed/kopiko-coffee-candy-100g/400/400",
  },
  // ── Canned Goods (cat-05) ────────────────────────────────────────
  {
    id: "can-001", categoryId: "cat-05",
    name: "555 Sardines in Tomato Sauce 155g", slug: "555-sardines-tomato-155g", brand: "555",
    unit: "can", unitSize: "155g", price: 28, srp: 35, sku: "555-SAR-TOM",
    minOrderQty: 24, isActive: true, isFeatured: true, stock: 960, lowStockThreshold: 96,
    createdAt: "2024-01-01T00:00:00Z", description: "555 Sardines in tomato sauce, 155g can.",
    imageUrl: "https://picsum.photos/seed/555-sardines-tomato-155g/400/400",
  },
  {
    id: "can-002", categoryId: "cat-05",
    name: "Century Tuna Flakes in Oil 180g", slug: "century-tuna-flakes-oil-180g", brand: "Century Tuna",
    unit: "can", unitSize: "180g", price: 42, srp: 52, sku: "CTU-FLK-180",
    minOrderQty: 24, isActive: true, isFeatured: true, stock: 720, lowStockThreshold: 72,
    createdAt: "2024-01-01T00:00:00Z", description: "Century Tuna flakes in oil, 180g can.",
    imageUrl: "https://picsum.photos/seed/century-tuna-flakes-oil-180g/400/400",
  },
  {
    id: "can-003", categoryId: "cat-05",
    name: "Mega Sardines Hot and Spicy 155g", slug: "mega-sardines-hot-spicy-155g", brand: "Mega",
    unit: "can", unitSize: "155g", price: 26, srp: 32, sku: "MEG-SAR-SPY",
    minOrderQty: 24, isActive: true, isFeatured: false, stock: 480, lowStockThreshold: 48,
    createdAt: "2024-01-01T00:00:00Z", description: "Mega Sardines in hot and spicy sauce, 155g can.",
    imageUrl: "https://picsum.photos/seed/mega-sardines-hot-spicy-155g/400/400",
  },
  {
    id: "can-004", categoryId: "cat-05",
    name: "Argentina Corned Beef 260g", slug: "argentina-corned-beef-260g", brand: "Argentina",
    unit: "can", unitSize: "260g", price: 85, srp: 105, sku: "ARG-CRB-260",
    minOrderQty: 12, isActive: true, isFeatured: false, stock: 480, lowStockThreshold: 48,
    createdAt: "2024-01-01T00:00:00Z", description: "Argentina corned beef with natural juices, 260g can.",
    imageUrl: "https://picsum.photos/seed/argentina-corned-beef-260g/400/400",
  },
  {
    id: "can-005", categoryId: "cat-05",
    name: "Del Monte Tomato Sauce 250g", slug: "del-monte-tomato-sauce-250g", brand: "Del Monte",
    unit: "pack", unitSize: "250g", price: 28, srp: 35, sku: "DLM-TOM-250",
    minOrderQty: 24, isActive: true, isFeatured: false, stock: 360, lowStockThreshold: 36,
    createdAt: "2024-01-01T00:00:00Z", description: "Del Monte tomato sauce, 250g pack.",
    imageUrl: "https://picsum.photos/seed/del-monte-tomato-sauce-250g/400/400",
  },
  // ── Beverages (cat-06) ───────────────────────────────────────────
  {
    id: "bev-001", categoryId: "cat-06",
    name: "Coca-Cola Regular 330ml", slug: "coca-cola-330ml", brand: "Coca-Cola",
    unit: "can", unitSize: "330ml", price: 28, srp: 35, sku: "CC-330-REG",
    minOrderQty: 24, isActive: true, isFeatured: true, stock: 480, lowStockThreshold: 48,
    createdAt: "2024-01-01T00:00:00Z", description: "Classic Coca-Cola in 330ml can. 24 cans per case.",
    imageUrl: "https://picsum.photos/seed/coca-cola-330ml/400/400",
  },
  {
    id: "bev-002", categoryId: "cat-06",
    name: "Sprite Lemon-Lime 330ml", slug: "sprite-330ml", brand: "Sprite",
    unit: "can", unitSize: "330ml", price: 28, srp: 35, sku: "SPR-330-LEM",
    minOrderQty: 24, isActive: true, isFeatured: false, stock: 480, lowStockThreshold: 48,
    createdAt: "2024-01-01T00:00:00Z", description: "Sprite lemon-lime carbonated drink, 330ml can.",
    imageUrl: "https://picsum.photos/seed/sprite-330ml/400/400",
  },
  {
    id: "bev-003", categoryId: "cat-06",
    name: "Wilkins Pure Distilled Water 500ml", slug: "wilkins-water-500ml", brand: "Wilkins",
    unit: "bottle", unitSize: "500ml", price: 12, srp: 15, sku: "WLK-500-PUR",
    minOrderQty: 24, isActive: true, isFeatured: false, stock: 240, lowStockThreshold: 24,
    createdAt: "2024-01-01T00:00:00Z", description: "Wilkins pure distilled water, 500ml bottle.",
    imageUrl: "https://picsum.photos/seed/wilkins-water-500ml/400/400",
  },
  {
    id: "bev-004", categoryId: "cat-06",
    name: "Royal True Orange 355ml", slug: "royal-true-orange-355ml", brand: "Royal",
    unit: "can", unitSize: "355ml", price: 26, srp: 32, sku: "RTO-355-CAN",
    minOrderQty: 24, isActive: true, isFeatured: false, stock: 288, lowStockThreshold: 48,
    createdAt: "2024-01-01T00:00:00Z", description: "Royal True Orange carbonated drink, 355ml can.",
    imageUrl: "https://picsum.photos/seed/royal-true-orange-355ml/400/400",
  },
  {
    id: "bev-005", categoryId: "cat-06",
    name: "C2 Green Tea Lemon 500ml", slug: "c2-green-tea-lemon-500ml", brand: "C2",
    unit: "bottle", unitSize: "500ml", price: 18, srp: 22, sku: "C2-GTE-500",
    minOrderQty: 24, isActive: true, isFeatured: false, stock: 360, lowStockThreshold: 36,
    createdAt: "2024-01-01T00:00:00Z", description: "C2 ready-to-drink green tea with lemon, 500ml.",
    imageUrl: "https://picsum.photos/seed/c2-green-tea-lemon-500ml/400/400",
  },
  {
    id: "bev-006", categoryId: "cat-06",
    name: "Sting Energy Drink Red 330ml", slug: "sting-energy-drink-330ml", brand: "Sting",
    unit: "can", unitSize: "330ml", price: 28, srp: 35, sku: "STG-RED-330",
    minOrderQty: 24, isActive: true, isFeatured: false, stock: 360, lowStockThreshold: 36,
    createdAt: "2024-01-01T00:00:00Z", description: "Sting berry blast energy drink, 330ml can.",
    imageUrl: "https://picsum.photos/seed/sting-energy-drink-330ml/400/400",
  },
  // ── Powdered Drinks (cat-07) ─────────────────────────────────────
  {
    id: "pwd-001", categoryId: "cat-07",
    name: "Milo Activ-Go 3-in-1 27g x 10", slug: "milo-3in1-27g-x10", brand: "Milo",
    unit: "pack", unitSize: "27g x 10 sachets", price: 125, srp: 155, sku: "MIL-3IN1-10",
    minOrderQty: 24, isActive: true, isFeatured: true, stock: 720, lowStockThreshold: 72,
    createdAt: "2024-01-01T00:00:00Z", description: "Milo Activ-Go 3-in-1 chocolate malt drink, 27g x 10 sachets.",
    imageUrl: "https://picsum.photos/seed/milo-3in1-27g-x10/400/400",
  },
  {
    id: "pwd-002", categoryId: "cat-07",
    name: "Tang Orange Flavor 25g x 10", slug: "tang-orange-25g-x10", brand: "Tang",
    unit: "pack", unitSize: "25g x 10 sachets", price: 45, srp: 58, sku: "TNG-ORA-10",
    minOrderQty: 24, isActive: true, isFeatured: false, stock: 480, lowStockThreshold: 48,
    createdAt: "2024-01-01T00:00:00Z", description: "Tang orange powdered juice drink, 25g x 10 sachets.",
    imageUrl: "https://picsum.photos/seed/tang-orange-25g-x10/400/400",
  },
  {
    id: "pwd-003", categoryId: "cat-07",
    name: "Nestea Lemon Iced Tea Powder 25g x 10", slug: "nestea-lemon-powder-25g-x10", brand: "Nestea",
    unit: "pack", unitSize: "25g x 10 sachets", price: 50, srp: 62, sku: "NES-ICT-10",
    minOrderQty: 24, isActive: true, isFeatured: false, stock: 360, lowStockThreshold: 36,
    createdAt: "2024-01-01T00:00:00Z", description: "Nestea lemon iced tea powdered drink, 25g x 10 sachets.",
    imageUrl: "https://picsum.photos/seed/nestea-lemon-powder-25g-x10/400/400",
  },
  {
    id: "pwd-004", categoryId: "cat-07",
    name: "Ovaltine Classic Malt Drink 300g", slug: "ovaltine-classic-300g", brand: "Ovaltine",
    unit: "jar", unitSize: "300g", price: 110, srp: 138, sku: "OVL-CLS-300",
    minOrderQty: 12, isActive: true, isFeatured: false, stock: 240, lowStockThreshold: 24,
    createdAt: "2024-01-01T00:00:00Z", description: "Ovaltine classic malt drink powder, 300g jar.",
    imageUrl: "https://picsum.photos/seed/ovaltine-classic-300g/400/400",
  },
  // ── Milk (cat-08) ────────────────────────────────────────────────
  {
    id: "mlk-001", categoryId: "cat-08",
    name: "Bear Brand Sterilized Powdered Milk 155g", slug: "bear-brand-powdered-155g", brand: "Bear Brand",
    unit: "pack", unitSize: "155g", price: 58, srp: 72, sku: "BB-PWD-155",
    minOrderQty: 24, isActive: true, isFeatured: true, stock: 480, lowStockThreshold: 48,
    createdAt: "2024-01-01T00:00:00Z", description: "Bear Brand sterilized powdered milk drink, 155g.",
    imageUrl: "https://picsum.photos/seed/bear-brand-powdered-155g/400/400",
  },
  {
    id: "mlk-002", categoryId: "cat-08",
    name: "Alaska Powdered Milk Drink 150g", slug: "alaska-powdered-milk-150g", brand: "Alaska",
    unit: "pack", unitSize: "150g", price: 62, srp: 78, sku: "ALS-PWD-150",
    minOrderQty: 24, isActive: true, isFeatured: false, stock: 480, lowStockThreshold: 48,
    createdAt: "2024-01-01T00:00:00Z", description: "Alaska powdered full-cream milk drink, 150g.",
    imageUrl: "https://picsum.photos/seed/alaska-powdered-milk-150g/400/400",
  },
  {
    id: "mlk-003", categoryId: "cat-08",
    name: "Alaska Evaporated Filled Milk 370ml", slug: "alaska-evaporated-milk-370ml", brand: "Alaska",
    unit: "can", unitSize: "370ml", price: 28, srp: 35, sku: "ALS-EVP-370",
    minOrderQty: 24, isActive: true, isFeatured: false, stock: 360, lowStockThreshold: 36,
    createdAt: "2024-01-01T00:00:00Z", description: "Alaska evaporated filled milk, 370ml can.",
    imageUrl: "https://picsum.photos/seed/alaska-evaporated-milk-370ml/400/400",
  },
  {
    id: "mlk-004", categoryId: "cat-08",
    name: "Carnation All-Purpose Cream 250ml", slug: "carnation-all-purpose-cream-250ml", brand: "Carnation",
    unit: "pack", unitSize: "250ml", price: 38, srp: 48, sku: "CAR-APC-250",
    minOrderQty: 24, isActive: true, isFeatured: false, stock: 240, lowStockThreshold: 24,
    createdAt: "2024-01-01T00:00:00Z", description: "Carnation all-purpose cream, 250ml pack.",
    imageUrl: "https://picsum.photos/seed/carnation-all-purpose-cream-250ml/400/400",
  },
  // ── Condiments & Sauces (cat-09) ─────────────────────────────────
  {
    id: "con-001", categoryId: "cat-09",
    name: "Silver Swan Soy Sauce 1L", slug: "silver-swan-soy-sauce-1l", brand: "Silver Swan",
    unit: "bottle", unitSize: "1L", price: 62, srp: 78, sku: "SS-SOY-1L",
    minOrderQty: 12, isActive: true, isFeatured: true, stock: 480, lowStockThreshold: 48,
    createdAt: "2024-01-01T00:00:00Z", description: "Silver Swan regular soy sauce, 1 liter bottle.",
    imageUrl: "https://picsum.photos/seed/silver-swan-soy-sauce-1l/400/400",
  },
  {
    id: "con-002", categoryId: "cat-09",
    name: "Datu Puti Sukang Maasim 1L", slug: "datu-puti-vinegar-1l", brand: "Datu Puti",
    unit: "bottle", unitSize: "1L", price: 48, srp: 60, sku: "DP-VIN-1L",
    minOrderQty: 12, isActive: true, isFeatured: false, stock: 360, lowStockThreshold: 36,
    createdAt: "2024-01-01T00:00:00Z", description: "Datu Puti native cane vinegar, 1 liter bottle.",
    imageUrl: "https://picsum.photos/seed/datu-puti-vinegar-1l/400/400",
  },
  {
    id: "con-003", categoryId: "cat-09",
    name: "UFC Banana Ketchup 320g", slug: "ufc-banana-ketchup-320g", brand: "UFC",
    unit: "bottle", unitSize: "320g", price: 42, srp: 52, sku: "UFC-BAN-320",
    minOrderQty: 12, isActive: true, isFeatured: false, stock: 360, lowStockThreshold: 36,
    createdAt: "2024-01-01T00:00:00Z", description: "UFC banana ketchup original flavor, 320g squeeze bottle.",
    imageUrl: "https://picsum.photos/seed/ufc-banana-ketchup-320g/400/400",
  },
  {
    id: "con-004", categoryId: "cat-09",
    name: "Knorr Sinigang sa Sampaloc Mix 40g", slug: "knorr-sinigang-mix-40g", brand: "Knorr",
    unit: "pack", unitSize: "40g", price: 18, srp: 24, sku: "KNR-SIN-40",
    minOrderQty: 24, isActive: true, isFeatured: false, stock: 480, lowStockThreshold: 48,
    createdAt: "2024-01-01T00:00:00Z", description: "Knorr sinigang sa sampaloc tamarind soup base mix, 40g.",
    imageUrl: "https://picsum.photos/seed/knorr-sinigang-mix-40g/400/400",
  },
  {
    id: "con-005", categoryId: "cat-09",
    name: "Magic Sarap Seasoning Granules 8g x 12", slug: "magic-sarap-8g-x12", brand: "Magic Sarap",
    unit: "pack", unitSize: "8g x 12 sachets", price: 55, srp: 68, sku: "MGS-8G-12",
    minOrderQty: 24, isActive: true, isFeatured: false, stock: 480, lowStockThreshold: 48,
    createdAt: "2024-01-01T00:00:00Z", description: "Magic Sarap all-in-one seasoning granules, 8g x 12 sachets.",
    imageUrl: "https://picsum.photos/seed/magic-sarap-8g-x12/400/400",
  },
  // ── Cooking Essentials (cat-10) ──────────────────────────────────
  {
    id: "cke-001", categoryId: "cat-10",
    name: "Golden Fiesta Palm Oil 1L", slug: "golden-fiesta-palm-oil-1l", brand: "Golden Fiesta",
    unit: "bottle", unitSize: "1L", price: 82, srp: 100, sku: "GF-OIL-1L",
    minOrderQty: 12, isActive: true, isFeatured: true, stock: 360, lowStockThreshold: 36,
    createdAt: "2024-01-01T00:00:00Z", description: "Golden Fiesta pure palm oil for cooking, 1 liter bottle.",
    imageUrl: "https://picsum.photos/seed/golden-fiesta-palm-oil-1l/400/400",
  },
  {
    id: "cke-002", categoryId: "cat-10",
    name: "White Refined Sugar 1kg", slug: "white-refined-sugar-1kg", brand: "Refined Sugar",
    unit: "pack", unitSize: "1kg", price: 68, srp: 82, sku: "SUG-WHT-1KG",
    minOrderQty: 12, isActive: true, isFeatured: false, stock: 240, lowStockThreshold: 24,
    createdAt: "2024-01-01T00:00:00Z", description: "White refined sugar, 1kg pack.",
    imageUrl: "https://picsum.photos/seed/white-refined-sugar-1kg/400/400",
  },
  {
    id: "cke-003", categoryId: "cat-10",
    name: "Iodized Salt 250g", slug: "iodized-salt-250g", brand: "Rock Salt",
    unit: "pack", unitSize: "250g", price: 18, srp: 22, sku: "SAL-IOD-250",
    minOrderQty: 24, isActive: true, isFeatured: false, stock: 480, lowStockThreshold: 48,
    createdAt: "2024-01-01T00:00:00Z", description: "Refined iodized salt, 250g pack.",
    imageUrl: "https://picsum.photos/seed/iodized-salt-250g/400/400",
  },
  {
    id: "cke-004", categoryId: "cat-10",
    name: "Maya All-Purpose Flour 1kg", slug: "maya-all-purpose-flour-1kg", brand: "Maya",
    unit: "pack", unitSize: "1kg", price: 52, srp: 65, sku: "MAY-APF-1KG",
    minOrderQty: 12, isActive: true, isFeatured: false, stock: 240, lowStockThreshold: 24,
    createdAt: "2024-01-01T00:00:00Z", description: "Maya all-purpose flour, 1kg pack.",
    imageUrl: "https://picsum.photos/seed/maya-all-purpose-flour-1kg/400/400",
  },
  // ── Bread Spreads (cat-11) ───────────────────────────────────────
  {
    id: "spr-001", categoryId: "cat-11",
    name: "Star Margarine Original 100g", slug: "star-margarine-100g", brand: "Star Margarine",
    unit: "tub", unitSize: "100g", price: 28, srp: 35, sku: "STR-MAR-100",
    minOrderQty: 24, isActive: true, isFeatured: false, stock: 480, lowStockThreshold: 48,
    createdAt: "2024-01-01T00:00:00Z", description: "Star margarine original flavor, 100g tub.",
    imageUrl: "https://picsum.photos/seed/star-margarine-100g/400/400",
  },
  {
    id: "spr-002", categoryId: "cat-11",
    name: "Lily's Peanut Butter Creamy 200g", slug: "lilys-peanut-butter-200g", brand: "Lily's",
    unit: "jar", unitSize: "200g", price: 58, srp: 72, sku: "LIL-PB-200",
    minOrderQty: 12, isActive: true, isFeatured: false, stock: 240, lowStockThreshold: 24,
    createdAt: "2024-01-01T00:00:00Z", description: "Lily's peanut butter creamy spread, 200g jar.",
    imageUrl: "https://picsum.photos/seed/lilys-peanut-butter-200g/400/400",
  },
  {
    id: "spr-003", categoryId: "cat-11",
    name: "Cheez Whiz Original Cheese Spread 165g", slug: "cheez-whiz-original-165g", brand: "Cheez Whiz",
    unit: "jar", unitSize: "165g", price: 85, srp: 105, sku: "CWZ-ORI-165",
    minOrderQty: 12, isActive: true, isFeatured: false, stock: 240, lowStockThreshold: 24,
    createdAt: "2024-01-01T00:00:00Z", description: "Cheez Whiz original processed cheese spread, 165g jar.",
    imageUrl: "https://picsum.photos/seed/cheez-whiz-original-165g/400/400",
  },
  // ── Bread & Bakery (cat-12) ──────────────────────────────────────
  {
    id: "brd-001", categoryId: "cat-12",
    name: "Gardenia Classic White Bread 400g", slug: "gardenia-classic-white-bread-400g", brand: "Gardenia",
    unit: "loaf", unitSize: "400g", price: 55, srp: 68, sku: "GAR-CWB-400",
    minOrderQty: 12, isActive: true, isFeatured: true, stock: 120, lowStockThreshold: 12,
    createdAt: "2024-01-01T00:00:00Z", description: "Gardenia classic white sliced bread, 400g loaf.",
    imageUrl: "https://picsum.photos/seed/gardenia-classic-white-bread-400g/400/400",
  },
  {
    id: "brd-002", categoryId: "cat-12",
    name: "Gardenia Wheat Bread 400g", slug: "gardenia-wheat-bread-400g", brand: "Gardenia",
    unit: "loaf", unitSize: "400g", price: 62, srp: 76, sku: "GAR-WHT-400",
    minOrderQty: 12, isActive: true, isFeatured: false, stock: 96, lowStockThreshold: 12,
    createdAt: "2024-01-01T00:00:00Z", description: "Gardenia wheat sliced bread, 400g loaf.",
    imageUrl: "https://picsum.photos/seed/gardenia-wheat-bread-400g/400/400",
  },
  {
    id: "brd-003", categoryId: "cat-12",
    name: "Monde Ensaymada 60g", slug: "monde-ensaymada-60g", brand: "Monde",
    unit: "piece", unitSize: "60g", price: 18, srp: 22, sku: "MON-ENS-60",
    minOrderQty: 24, isActive: true, isFeatured: false, stock: 240, lowStockThreshold: 24,
    createdAt: "2024-01-01T00:00:00Z", description: "Monde ensaymada sweet bread roll, 60g.",
    imageUrl: "https://picsum.photos/seed/monde-ensaymada-60g/400/400",
  },
  // ── Eggs (cat-13) ────────────────────────────────────────────────
  {
    id: "egg-001", categoryId: "cat-13",
    name: "Chicken Eggs Large Tray 30pcs", slug: "chicken-eggs-tray-30", brand: "Farm Fresh",
    unit: "tray", unitSize: "30 pieces", price: 185, srp: 220, sku: "EGG-LRG-30",
    minOrderQty: 5, isActive: true, isFeatured: true, stock: 60, lowStockThreshold: 10,
    createdAt: "2024-01-01T00:00:00Z", description: "Large fresh chicken eggs, tray of 30 pieces.",
    imageUrl: "https://picsum.photos/seed/chicken-eggs-tray-30/400/400",
  },
  {
    id: "egg-002", categoryId: "cat-13",
    name: "Chicken Eggs Large per piece", slug: "chicken-eggs-per-piece", brand: "Farm Fresh",
    unit: "piece", unitSize: "1 piece", price: 8, srp: 10, sku: "EGG-LRG-1",
    minOrderQty: 30, isActive: true, isFeatured: false, stock: 900, lowStockThreshold: 90,
    createdAt: "2024-01-01T00:00:00Z", description: "Large fresh chicken egg, sold per piece.",
    imageUrl: "https://picsum.photos/seed/chicken-eggs-per-piece/400/400",
  },
  {
    id: "egg-003", categoryId: "cat-13",
    name: "Salted Eggs per piece", slug: "salted-eggs-per-piece", brand: "Local",
    unit: "piece", unitSize: "1 piece", price: 18, srp: 22, sku: "EGG-SLT-1",
    minOrderQty: 12, isActive: true, isFeatured: false, stock: 120, lowStockThreshold: 24,
    createdAt: "2024-01-01T00:00:00Z", description: "Locally prepared salted duck egg, sold per piece.",
    imageUrl: "https://picsum.photos/seed/salted-eggs-per-piece/400/400",
  },
  // ── Rice (cat-14) ────────────────────────────────────────────────
  {
    id: "ric-001", categoryId: "cat-14",
    name: "Premium Jasmine Rice 5kg", slug: "premium-jasmine-rice-5kg", brand: "Dona Maria",
    unit: "sack", unitSize: "5kg", price: 265, srp: 320, sku: "RIC-JAS-5KG",
    minOrderQty: 5, isActive: true, isFeatured: true, stock: 100, lowStockThreshold: 10,
    createdAt: "2024-01-01T00:00:00Z", description: "Premium jasmine rice, fragrant and well-milled, 5kg sack.",
    imageUrl: "https://picsum.photos/seed/premium-jasmine-rice-5kg/400/400",
  },
  {
    id: "ric-002", categoryId: "cat-14",
    name: "Well-Milled Rice 5kg", slug: "well-milled-rice-5kg", brand: "Local Brand",
    unit: "sack", unitSize: "5kg", price: 245, srp: 295, sku: "RIC-WML-5KG",
    minOrderQty: 5, isActive: true, isFeatured: false, stock: 80, lowStockThreshold: 10,
    createdAt: "2024-01-01T00:00:00Z", description: "Well-milled white rice, 5kg sack.",
    imageUrl: "https://picsum.photos/seed/well-milled-rice-5kg/400/400",
  },
  {
    id: "ric-003", categoryId: "cat-14",
    name: "Regular Milled Rice 5kg", slug: "regular-milled-rice-5kg", brand: "Local Brand",
    unit: "sack", unitSize: "5kg", price: 225, srp: 270, sku: "RIC-REG-5KG",
    minOrderQty: 5, isActive: true, isFeatured: false, stock: 80, lowStockThreshold: 10,
    createdAt: "2024-01-01T00:00:00Z", description: "Regular milled rice, 5kg sack.",
    imageUrl: "https://picsum.photos/seed/regular-milled-rice-5kg/400/400",
  },
  {
    id: "ric-004", categoryId: "cat-14",
    name: "Sinandomeng Rice 5kg", slug: "sinandomeng-rice-5kg", brand: "Sinandomeng",
    unit: "sack", unitSize: "5kg", price: 255, srp: 308, sku: "RIC-SIN-5KG",
    minOrderQty: 5, isActive: true, isFeatured: false, stock: 60, lowStockThreshold: 10,
    createdAt: "2024-01-01T00:00:00Z", description: "Sinandomeng variety premium rice, 5kg sack.",
    imageUrl: "https://picsum.photos/seed/sinandomeng-rice-5kg/400/400",
  },
  // ── Frozen & Chilled (cat-15) ────────────────────────────────────
  {
    id: "fro-001", categoryId: "cat-15",
    name: "Purefoods Tender Juicy Hotdog 250g", slug: "purefoods-tender-juicy-hotdog-250g", brand: "Purefoods",
    unit: "pack", unitSize: "250g", price: 68, srp: 85, sku: "PF-TJH-250",
    minOrderQty: 12, isActive: true, isFeatured: true, stock: 240, lowStockThreshold: 24,
    createdAt: "2024-01-01T00:00:00Z", description: "Purefoods Tender Juicy classic hotdog, 250g pack.",
    imageUrl: "https://picsum.photos/seed/purefoods-tender-juicy-hotdog-250g/400/400",
  },
  {
    id: "fro-002", categoryId: "cat-15",
    name: "CDO Sweet Style Tocino 500g", slug: "cdo-sweet-tocino-500g", brand: "CDO",
    unit: "pack", unitSize: "500g", price: 95, srp: 118, sku: "CDO-TOC-500",
    minOrderQty: 12, isActive: true, isFeatured: false, stock: 180, lowStockThreshold: 18,
    createdAt: "2024-01-01T00:00:00Z", description: "CDO Fiesta sweet style tocino, 500g pack.",
    imageUrl: "https://picsum.photos/seed/cdo-sweet-tocino-500g/400/400",
  },
  {
    id: "fro-003", categoryId: "cat-15",
    name: "CDO Chicken Nuggets 400g", slug: "cdo-chicken-nuggets-400g", brand: "CDO",
    unit: "pack", unitSize: "400g", price: 98, srp: 122, sku: "CDO-NUG-400",
    minOrderQty: 12, isActive: true, isFeatured: false, stock: 120, lowStockThreshold: 12,
    createdAt: "2024-01-01T00:00:00Z", description: "CDO chicken nuggets, breaded and frozen, 400g pack.",
    imageUrl: "https://picsum.photos/seed/cdo-chicken-nuggets-400g/400/400",
  },
  {
    id: "fro-004", categoryId: "cat-15",
    name: "Selecta Chocolate Ice Cream 1.4L", slug: "selecta-chocolate-ice-cream-1-4l", brand: "Selecta",
    unit: "tub", unitSize: "1.4L", price: 155, srp: 192, sku: "SEL-CHO-1.4",
    minOrderQty: 6, isActive: true, isFeatured: false, stock: 60, lowStockThreshold: 6,
    createdAt: "2024-01-01T00:00:00Z", description: "Selecta chocolate ice cream, 1.4L tub.",
    imageUrl: "https://picsum.photos/seed/selecta-chocolate-ice-cream-1-4l/400/400",
  },
  // ── Personal Care (cat-16) ───────────────────────────────────────
  {
    id: "per-001", categoryId: "cat-16",
    name: "Safeguard Classic Antibacterial Bar Soap 135g", slug: "safeguard-classic-bar-soap-135g", brand: "Safeguard",
    unit: "bar", unitSize: "135g", price: 38, srp: 48, sku: "SFG-CLA-135",
    minOrderQty: 24, isActive: true, isFeatured: true, stock: 720, lowStockThreshold: 72,
    createdAt: "2024-01-01T00:00:00Z", description: "Safeguard Classic antibacterial bar soap, 135g.",
    imageUrl: "https://picsum.photos/seed/safeguard-classic-bar-soap-135g/400/400",
  },
  {
    id: "per-002", categoryId: "cat-16",
    name: "Palmolive Naturals Bar Soap 80g", slug: "palmolive-naturals-bar-80g", brand: "Palmolive",
    unit: "bar", unitSize: "80g", price: 22, srp: 28, sku: "PLM-NAT-80",
    minOrderQty: 24, isActive: true, isFeatured: false, stock: 480, lowStockThreshold: 48,
    createdAt: "2024-01-01T00:00:00Z", description: "Palmolive Naturals bar soap with moisturizing milk, 80g.",
    imageUrl: "https://picsum.photos/seed/palmolive-naturals-bar-80g/400/400",
  },
  {
    id: "per-003", categoryId: "cat-16",
    name: "Sunsilk Smooth and Manageable Shampoo 180ml", slug: "sunsilk-smooth-shampoo-180ml", brand: "Sunsilk",
    unit: "bottle", unitSize: "180ml", price: 62, srp: 78, sku: "SSL-SMO-180",
    minOrderQty: 12, isActive: true, isFeatured: false, stock: 360, lowStockThreshold: 36,
    createdAt: "2024-01-01T00:00:00Z", description: "Sunsilk Smooth and Manageable shampoo with egg protein, 180ml.",
    imageUrl: "https://picsum.photos/seed/sunsilk-smooth-shampoo-180ml/400/400",
  },
  {
    id: "per-004", categoryId: "cat-16",
    name: "Colgate Fluoride Toothpaste 75ml", slug: "colgate-fluoride-toothpaste-75ml", brand: "Colgate",
    unit: "tube", unitSize: "75ml", price: 38, srp: 48, sku: "CLG-FLR-75",
    minOrderQty: 12, isActive: true, isFeatured: false, stock: 360, lowStockThreshold: 36,
    createdAt: "2024-01-01T00:00:00Z", description: "Colgate fluoride toothpaste for cavity protection, 75ml.",
    imageUrl: "https://picsum.photos/seed/colgate-fluoride-toothpaste-75ml/400/400",
  },
  {
    id: "per-005", categoryId: "cat-16",
    name: "Rexona Women Powder Dry Roll-On 50ml", slug: "rexona-women-powder-dry-50ml", brand: "Rexona",
    unit: "bottle", unitSize: "50ml", price: 78, srp: 98, sku: "REX-WPD-50",
    minOrderQty: 12, isActive: true, isFeatured: false, stock: 240, lowStockThreshold: 24,
    createdAt: "2024-01-01T00:00:00Z", description: "Rexona Women Powder Dry 48h protection deodorant roll-on, 50ml.",
    imageUrl: "https://picsum.photos/seed/rexona-women-powder-dry-50ml/400/400",
  },
  // ── Feminine Care (cat-17) ───────────────────────────────────────
  {
    id: "fem-001", categoryId: "cat-17",
    name: "Modess Regular Sanitary Napkin 8pcs", slug: "modess-regular-napkin-8pcs", brand: "Modess",
    unit: "pack", unitSize: "8 pads", price: 42, srp: 52, sku: "MOD-REG-8",
    minOrderQty: 12, isActive: true, isFeatured: false, stock: 360, lowStockThreshold: 36,
    createdAt: "2024-01-01T00:00:00Z", description: "Modess regular sanitary napkin with wings, 8 pads per pack.",
    imageUrl: "https://picsum.photos/seed/modess-regular-napkin-8pcs/400/400",
  },
  {
    id: "fem-002", categoryId: "cat-17",
    name: "Whisper Ultra Thin Wings 8pcs", slug: "whisper-ultra-thin-8pcs", brand: "Whisper",
    unit: "pack", unitSize: "8 pads", price: 55, srp: 68, sku: "WHI-UTW-8",
    minOrderQty: 12, isActive: true, isFeatured: false, stock: 240, lowStockThreshold: 24,
    createdAt: "2024-01-01T00:00:00Z", description: "Whisper Ultra Thin with wings sanitary napkin, 8 pads per pack.",
    imageUrl: "https://picsum.photos/seed/whisper-ultra-thin-8pcs/400/400",
  },
  {
    id: "fem-003", categoryId: "cat-17",
    name: "Charmee Panty Liner Regular 20pcs", slug: "charmee-panty-liner-regular-20pcs", brand: "Charmee",
    unit: "pack", unitSize: "20 liners", price: 35, srp: 45, sku: "CHA-PLN-20",
    minOrderQty: 12, isActive: true, isFeatured: false, stock: 240, lowStockThreshold: 24,
    createdAt: "2024-01-01T00:00:00Z", description: "Charmee regular panty liner, 20 liners per pack.",
    imageUrl: "https://picsum.photos/seed/charmee-panty-liner-regular-20pcs/400/400",
  },
  // ── Laundry (cat-18) ─────────────────────────────────────────────
  {
    id: "lau-001", categoryId: "cat-18",
    name: "Surf Powder Detergent 66g x 6", slug: "surf-powder-detergent-66g-x6", brand: "Surf",
    unit: "pack", unitSize: "66g x 6 sachets", price: 38, srp: 48, sku: "SURF-PWD-66",
    minOrderQty: 24, isActive: true, isFeatured: true, stock: 720, lowStockThreshold: 72,
    createdAt: "2024-01-01T00:00:00Z", description: "Surf powder detergent in summer fresh scent, 66g x 6 sachets.",
    imageUrl: "https://picsum.photos/seed/surf-powder-detergent-66g-x6/400/400",
  },
  {
    id: "lau-002", categoryId: "cat-18",
    name: "Ariel Powder Detergent with Downy 57g x 6", slug: "ariel-powder-detergent-57g-x6", brand: "Ariel",
    unit: "pack", unitSize: "57g x 6 sachets", price: 45, srp: 56, sku: "ARI-PWD-57",
    minOrderQty: 24, isActive: true, isFeatured: false, stock: 480, lowStockThreshold: 48,
    createdAt: "2024-01-01T00:00:00Z", description: "Ariel powder detergent with Downy fresh scent, 57g x 6 sachets.",
    imageUrl: "https://picsum.photos/seed/ariel-powder-detergent-57g-x6/400/400",
  },
  {
    id: "lau-003", categoryId: "cat-18",
    name: "Tide Antibac Powder Detergent 66g x 6", slug: "tide-antibac-powder-66g-x6", brand: "Tide",
    unit: "pack", unitSize: "66g x 6 sachets", price: 52, srp: 65, sku: "TDE-ANT-66",
    minOrderQty: 24, isActive: true, isFeatured: false, stock: 360, lowStockThreshold: 36,
    createdAt: "2024-01-01T00:00:00Z", description: "Tide Antibac powder detergent for clean and hygienic laundry, 66g x 6 sachets.",
    imageUrl: "https://picsum.photos/seed/tide-antibac-powder-66g-x6/400/400",
  },
  {
    id: "lau-004", categoryId: "cat-18",
    name: "Downy Sunrise Fresh Fabric Conditioner 27ml x 6", slug: "downy-sunrise-fresh-27ml-x6", brand: "Downy",
    unit: "pack", unitSize: "27ml x 6 sachets", price: 38, srp: 48, sku: "DOW-SRF-27",
    minOrderQty: 24, isActive: true, isFeatured: false, stock: 480, lowStockThreshold: 48,
    createdAt: "2024-01-01T00:00:00Z", description: "Downy Sunrise Fresh fabric conditioner, 27ml x 6 sachets.",
    imageUrl: "https://picsum.photos/seed/downy-sunrise-fresh-27ml-x6/400/400",
  },
  {
    id: "lau-005", categoryId: "cat-18",
    name: "Perla Laundry Bar Soap 380g", slug: "perla-laundry-bar-380g", brand: "Perla",
    unit: "bar", unitSize: "380g", price: 32, srp: 40, sku: "PER-LBS-380",
    minOrderQty: 12, isActive: true, isFeatured: false, stock: 360, lowStockThreshold: 36,
    createdAt: "2024-01-01T00:00:00Z", description: "Perla white laundry bar soap, 380g.",
    imageUrl: "https://picsum.photos/seed/perla-laundry-bar-380g/400/400",
  },
  // ── Household Cleaning (cat-19) ──────────────────────────────────
  {
    id: "hse-001", categoryId: "cat-19",
    name: "Joy Orange Dishwashing Liquid 250ml", slug: "joy-orange-dishwashing-250ml", brand: "Joy",
    unit: "bottle", unitSize: "250ml", price: 45, srp: 56, sku: "JOY-ORA-250",
    minOrderQty: 12, isActive: true, isFeatured: true, stock: 480, lowStockThreshold: 48,
    createdAt: "2024-01-01T00:00:00Z", description: "Joy orange dishwashing liquid with 2x cleaning power, 250ml.",
    imageUrl: "https://picsum.photos/seed/joy-orange-dishwashing-250ml/400/400",
  },
  {
    id: "hse-002", categoryId: "cat-19",
    name: "Axion Dishwashing Paste Calamansi 400g", slug: "axion-dishwashing-paste-400g", brand: "Axion",
    unit: "tub", unitSize: "400g", price: 38, srp: 48, sku: "AXN-CLM-400",
    minOrderQty: 12, isActive: true, isFeatured: false, stock: 360, lowStockThreshold: 36,
    createdAt: "2024-01-01T00:00:00Z", description: "Axion dishwashing paste with calamansi, 400g tub.",
    imageUrl: "https://picsum.photos/seed/axion-dishwashing-paste-400g/400/400",
  },
  {
    id: "hse-003", categoryId: "cat-19",
    name: "Domex Toilet Bowl Cleaner 500ml", slug: "domex-toilet-bowl-cleaner-500ml", brand: "Domex",
    unit: "bottle", unitSize: "500ml", price: 65, srp: 80, sku: "DOM-TBC-500",
    minOrderQty: 12, isActive: true, isFeatured: false, stock: 240, lowStockThreshold: 24,
    createdAt: "2024-01-01T00:00:00Z", description: "Domex toilet bowl cleaner with bleach action, 500ml.",
    imageUrl: "https://picsum.photos/seed/domex-toilet-bowl-cleaner-500ml/400/400",
  },
  {
    id: "hse-004", categoryId: "cat-19",
    name: "Zonrox Bleach Original 1L", slug: "zonrox-bleach-original-1l", brand: "Zonrox",
    unit: "bottle", unitSize: "1L", price: 38, srp: 48, sku: "ZNX-ORI-1L",
    minOrderQty: 12, isActive: true, isFeatured: false, stock: 360, lowStockThreshold: 36,
    createdAt: "2024-01-01T00:00:00Z", description: "Zonrox original bleach for clothes and household surfaces, 1L.",
    imageUrl: "https://picsum.photos/seed/zonrox-bleach-original-1l/400/400",
  },
  // ── Insecticides & Repellents (cat-20) ───────────────────────────
  {
    id: "ins-001", categoryId: "cat-20",
    name: "Baygon Multi-Insect Killer 600ml", slug: "baygon-multi-insect-killer-600ml", brand: "Baygon",
    unit: "can", unitSize: "600ml", price: 125, srp: 155, sku: "BAY-MIK-600",
    minOrderQty: 12, isActive: true, isFeatured: false, stock: 240, lowStockThreshold: 24,
    createdAt: "2024-01-01T00:00:00Z", description: "Baygon multi-insect killer aerosol spray, 600ml.",
    imageUrl: "https://picsum.photos/seed/baygon-multi-insect-killer-600ml/400/400",
  },
  {
    id: "ins-002", categoryId: "cat-20",
    name: "Katol Mosquito Coil 10pcs", slug: "katol-mosquito-coil-10pcs", brand: "Katol",
    unit: "pack", unitSize: "10 coils", price: 28, srp: 35, sku: "KAT-MSQ-10",
    minOrderQty: 24, isActive: true, isFeatured: true, stock: 480, lowStockThreshold: 48,
    createdAt: "2024-01-01T00:00:00Z", description: "Katol mosquito coil, 10 coils per pack.",
    imageUrl: "https://picsum.photos/seed/katol-mosquito-coil-10pcs/400/400",
  },
  {
    id: "ins-003", categoryId: "cat-20",
    name: "OFF Lotion Insect Repellent 100ml", slug: "off-lotion-insect-repellent-100ml", brand: "OFF",
    unit: "bottle", unitSize: "100ml", price: 48, srp: 60, sku: "OFF-LOT-100",
    minOrderQty: 12, isActive: true, isFeatured: false, stock: 240, lowStockThreshold: 24,
    createdAt: "2024-01-01T00:00:00Z", description: "OFF lotion insect repellent for mosquitoes and flies, 100ml.",
    imageUrl: "https://picsum.photos/seed/off-lotion-insect-repellent-100ml/400/400",
  },
  // ── Baby Products (cat-21) ───────────────────────────────────────
  {
    id: "bby-001", categoryId: "cat-21",
    name: "Pampers Baby Dry Newborn 12pcs", slug: "pampers-baby-dry-newborn-12pcs", brand: "Pampers",
    unit: "pack", unitSize: "12 diapers", price: 185, srp: 230, sku: "PAM-BDN-12",
    minOrderQty: 6, isActive: true, isFeatured: true, stock: 120, lowStockThreshold: 12,
    createdAt: "2024-01-01T00:00:00Z", description: "Pampers Baby Dry newborn diapers, up to 5kg, 12 pcs per pack.",
    imageUrl: "https://picsum.photos/seed/pampers-baby-dry-newborn-12pcs/400/400",
  },
  {
    id: "bby-002", categoryId: "cat-21",
    name: "Huggies Ultra Medium 10pcs", slug: "huggies-ultra-medium-10pcs", brand: "Huggies",
    unit: "pack", unitSize: "10 diapers", price: 172, srp: 215, sku: "HUG-ULM-10",
    minOrderQty: 6, isActive: true, isFeatured: false, stock: 120, lowStockThreshold: 12,
    createdAt: "2024-01-01T00:00:00Z", description: "Huggies Ultra medium diapers, 7-12kg, 10 pcs per pack.",
    imageUrl: "https://picsum.photos/seed/huggies-ultra-medium-10pcs/400/400",
  },
  {
    id: "bby-003", categoryId: "cat-21",
    name: "Johnson's Baby Powder Soft and Fresh 100g", slug: "johnsons-baby-powder-100g", brand: "Johnson's",
    unit: "bottle", unitSize: "100g", price: 48, srp: 60, sku: "JNS-BPW-100",
    minOrderQty: 12, isActive: true, isFeatured: false, stock: 360, lowStockThreshold: 36,
    createdAt: "2024-01-01T00:00:00Z", description: "Johnson's Baby Powder Soft and Fresh with soothing scent, 100g.",
    imageUrl: "https://picsum.photos/seed/johnsons-baby-powder-100g/400/400",
  },
  {
    id: "bby-004", categoryId: "cat-21",
    name: "Cerelac Rice and Milk Infant Cereal 200g", slug: "cerelac-rice-milk-200g", brand: "Cerelac",
    unit: "box", unitSize: "200g", price: 135, srp: 168, sku: "CER-RIC-200",
    minOrderQty: 6, isActive: true, isFeatured: false, stock: 120, lowStockThreshold: 12,
    createdAt: "2024-01-01T00:00:00Z", description: "Nestle Cerelac rice and milk infant cereal, fortified with iron, 200g.",
    imageUrl: "https://picsum.photos/seed/cerelac-rice-milk-200g/400/400",
  },
  // ── School & Office Supplies (cat-22) ────────────────────────────
  {
    id: "sch-001", categoryId: "cat-22",
    name: "Corona Composition Notebook 80 leaves", slug: "corona-composition-notebook-80l", brand: "Corona",
    unit: "piece", unitSize: "80 leaves", price: 22, srp: 28, sku: "COR-NB-80",
    minOrderQty: 12, isActive: true, isFeatured: false, stock: 360, lowStockThreshold: 36,
    createdAt: "2024-01-01T00:00:00Z", description: "Corona composition notebook, 80 leaves.",
    imageUrl: "https://picsum.photos/seed/corona-composition-notebook-80l/400/400",
  },
  {
    id: "sch-002", categoryId: "cat-22",
    name: "Panda Ballpen Blue 12pcs", slug: "panda-ballpen-blue-12pcs", brand: "Panda",
    unit: "box", unitSize: "12 pens", price: 42, srp: 52, sku: "PAN-BPB-12",
    minOrderQty: 12, isActive: true, isFeatured: false, stock: 240, lowStockThreshold: 24,
    createdAt: "2024-01-01T00:00:00Z", description: "Panda ballpen in blue ink, box of 12 pens.",
    imageUrl: "https://picsum.photos/seed/panda-ballpen-blue-12pcs/400/400",
  },
  {
    id: "sch-003", categoryId: "cat-22",
    name: "Mongol Pencil No. 2 12pcs", slug: "mongol-pencil-no2-12pcs", brand: "Mongol",
    unit: "box", unitSize: "12 pencils", price: 48, srp: 60, sku: "MON-PC2-12",
    minOrderQty: 12, isActive: true, isFeatured: false, stock: 240, lowStockThreshold: 24,
    createdAt: "2024-01-01T00:00:00Z", description: "Mongol No. 2 pencil, hexagonal, box of 12 pencils.",
    imageUrl: "https://picsum.photos/seed/mongol-pencil-no2-12pcs/400/400",
  },
  // ── OTC Health Products (cat-23) ─────────────────────────────────
  {
    id: "hlth-001", categoryId: "cat-23",
    name: "Biogesic Paracetamol 500mg 10tabs", slug: "biogesic-paracetamol-500mg-10tabs", brand: "Biogesic",
    unit: "pack", unitSize: "10 tablets", price: 28, srp: 35, sku: "BIO-PAR-10",
    minOrderQty: 12, isActive: true, isFeatured: true, stock: 720, lowStockThreshold: 72,
    createdAt: "2024-01-01T00:00:00Z", description: "Biogesic paracetamol 500mg for fever and pain relief, 10 tablets.",
    imageUrl: "https://picsum.photos/seed/biogesic-paracetamol-500mg-10tabs/400/400",
  },
  {
    id: "hlth-002", categoryId: "cat-23",
    name: "Enervon Multivitamins 30tabs", slug: "enervon-multivitamins-30tabs", brand: "Enervon",
    unit: "bottle", unitSize: "30 tablets", price: 145, srp: 180, sku: "ENV-MUL-30",
    minOrderQty: 6, isActive: true, isFeatured: false, stock: 240, lowStockThreshold: 24,
    createdAt: "2024-01-01T00:00:00Z", description: "Enervon multivitamins with B-complex, vitamin C, and minerals, 30 tablets.",
    imageUrl: "https://picsum.photos/seed/enervon-multivitamins-30tabs/400/400",
  },
  {
    id: "hlth-003", categoryId: "cat-23",
    name: "Green Cross Isopropyl Alcohol 70pct 500ml", slug: "green-cross-alcohol-500ml", brand: "Green Cross",
    unit: "bottle", unitSize: "500ml", price: 52, srp: 65, sku: "GCR-ALC-500",
    minOrderQty: 12, isActive: true, isFeatured: true, stock: 480, lowStockThreshold: 48,
    createdAt: "2024-01-01T00:00:00Z", description: "Green Cross 70% isopropyl alcohol for antiseptic use, 500ml.",
    imageUrl: "https://picsum.photos/seed/green-cross-alcohol-500ml/400/400",
  },
  {
    id: "hlth-004", categoryId: "cat-23",
    name: "Neozep Forte Cold and Flu 10tabs", slug: "neozep-forte-10tabs", brand: "Neozep",
    unit: "pack", unitSize: "10 tablets", price: 55, srp: 68, sku: "NEO-FOR-10",
    minOrderQty: 12, isActive: true, isFeatured: false, stock: 360, lowStockThreshold: 36,
    createdAt: "2024-01-01T00:00:00Z", description: "Neozep Forte non-drowsy cold and flu relief, 10 tablets.",
    imageUrl: "https://picsum.photos/seed/neozep-forte-10tabs/400/400",
  },
  {
    id: "hlth-005", categoryId: "cat-23",
    name: "Kremil-S Antacid Chewable Tablet 10tabs", slug: "kremil-s-antacid-10tabs", brand: "Kremil-S",
    unit: "pack", unitSize: "10 tablets", price: 35, srp: 44, sku: "KRM-ANT-10",
    minOrderQty: 12, isActive: true, isFeatured: false, stock: 360, lowStockThreshold: 36,
    createdAt: "2024-01-01T00:00:00Z", description: "Kremil-S antacid and anti-gas chewable tablet, 10 tablets.",
    imageUrl: "https://picsum.photos/seed/kremil-s-antacid-10tabs/400/400",
  },
  // ── Batteries & Lighters (cat-24) ────────────────────────────────
  {
    id: "bat-001", categoryId: "cat-24",
    name: "Eveready AA Batteries 4pcs", slug: "eveready-aa-batteries-4pcs", brand: "Eveready",
    unit: "pack", unitSize: "4 batteries", price: 45, srp: 56, sku: "EVR-AA-4",
    minOrderQty: 12, isActive: true, isFeatured: false, stock: 360, lowStockThreshold: 36,
    createdAt: "2024-01-01T00:00:00Z", description: "Eveready AA size alkaline batteries, pack of 4.",
    imageUrl: "https://picsum.photos/seed/eveready-aa-batteries-4pcs/400/400",
  },
  {
    id: "bat-002", categoryId: "cat-24",
    name: "Tokai Disposable Lighter 1pc", slug: "tokai-disposable-lighter-1pc", brand: "Tokai",
    unit: "piece", unitSize: "1 lighter", price: 18, srp: 22, sku: "TOK-LTR-1",
    minOrderQty: 24, isActive: true, isFeatured: false, stock: 480, lowStockThreshold: 48,
    createdAt: "2024-01-01T00:00:00Z", description: "Tokai disposable gas lighter, 1 piece.",
    imageUrl: "https://picsum.photos/seed/tokai-disposable-lighter-1pc/400/400",
  },
  {
    id: "bat-003", categoryId: "cat-24",
    name: "White Candles 8pcs", slug: "white-candles-8pcs", brand: "Generic",
    unit: "pack", unitSize: "8 candles", price: 28, srp: 35, sku: "CND-WHT-8",
    minOrderQty: 12, isActive: true, isFeatured: false, stock: 360, lowStockThreshold: 36,
    createdAt: "2024-01-01T00:00:00Z", description: "White household candles, pack of 8.",
    imageUrl: "https://picsum.photos/seed/white-candles-8pcs/400/400",
  },
  // ── Ice & Water (cat-25) ─────────────────────────────────────────
  {
    id: "ice-001", categoryId: "cat-25",
    name: "Tube Ice 5kg", slug: "tube-ice-5kg", brand: "Local",
    unit: "bag", unitSize: "5kg", price: 28, srp: 35, sku: "ICE-TUB-5KG",
    minOrderQty: 10, isActive: true, isFeatured: false, stock: 200, lowStockThreshold: 20,
    createdAt: "2024-01-01T00:00:00Z", description: "Purified tube ice, 5kg bag.",
    imageUrl: "https://picsum.photos/seed/tube-ice-5kg/400/400",
  },
  {
    id: "ice-002", categoryId: "cat-25",
    name: "Wilkins Purified Water 500ml", slug: "wilkins-purified-water-500ml", brand: "Wilkins",
    unit: "bottle", unitSize: "500ml", price: 12, srp: 15, sku: "WLK-PUR-500",
    minOrderQty: 24, isActive: true, isFeatured: false, stock: 240, lowStockThreshold: 24,
    createdAt: "2024-01-01T00:00:00Z", description: "Wilkins purified drinking water, 500ml bottle.",
    imageUrl: "https://picsum.photos/seed/wilkins-purified-water-500ml/400/400",
  },
  {
    id: "ice-003", categoryId: "cat-25",
    name: "Purified Water Refill per gallon", slug: "purified-water-refill-gallon", brand: "Local Station",
    unit: "gallon", unitSize: "5 gallons", price: 45, srp: 55, sku: "H2O-REF-5GAL",
    minOrderQty: 1, isActive: true, isFeatured: false, stock: 50, lowStockThreshold: 10,
    createdAt: "2024-01-01T00:00:00Z", description: "Purified water refill, per 5-gallon container.",
    imageUrl: "https://picsum.photos/seed/purified-water-refill-gallon/400/400",
  },
  // ── E-Load & Prepaid (cat-26) ────────────────────────────────────
  {
    id: "elo-001", categoryId: "cat-26",
    name: "Smart/TNT Load PHP 15", slug: "smart-tnt-load-15", brand: "Smart/TNT",
    unit: "load", unitSize: "PHP 15 worth", price: 14, srp: 15, sku: "ELO-SMT-15",
    minOrderQty: 1, isActive: true, isFeatured: false, stock: 0, lowStockThreshold: 0,
    createdAt: "2024-01-01T00:00:00Z", description: "Smart or TNT prepaid load worth PHP 15.",
    imageUrl: "https://picsum.photos/seed/smart-tnt-load-15/400/400",
  },
  {
    id: "elo-002", categoryId: "cat-26",
    name: "Smart/TNT Load PHP 30", slug: "smart-tnt-load-30", brand: "Smart/TNT",
    unit: "load", unitSize: "PHP 30 worth", price: 28, srp: 30, sku: "ELO-SMT-30",
    minOrderQty: 1, isActive: true, isFeatured: false, stock: 0, lowStockThreshold: 0,
    createdAt: "2024-01-01T00:00:00Z", description: "Smart or TNT prepaid load worth PHP 30.",
    imageUrl: "https://picsum.photos/seed/smart-tnt-load-30/400/400",
  },
  {
    id: "elo-003", categoryId: "cat-26",
    name: "Globe/TM Load PHP 15", slug: "globe-tm-load-15", brand: "Globe/TM",
    unit: "load", unitSize: "PHP 15 worth", price: 14, srp: 15, sku: "ELO-GLB-15",
    minOrderQty: 1, isActive: true, isFeatured: false, stock: 0, lowStockThreshold: 0,
    createdAt: "2024-01-01T00:00:00Z", description: "Globe or TM prepaid load worth PHP 15.",
    imageUrl: "https://picsum.photos/seed/globe-tm-load-15/400/400",
  },
  {
    id: "elo-004", categoryId: "cat-26",
    name: "GCash E-Wallet Cash-in Service", slug: "gcash-ewallet-cashin", brand: "GCash",
    unit: "service", unitSize: "variable", price: 0, srp: 0, sku: "ELO-GCS-SVC",
    minOrderQty: 1, isActive: true, isFeatured: false, stock: 0, lowStockThreshold: 0,
    createdAt: "2024-01-01T00:00:00Z", description: "GCash e-wallet cash-in service. Ask staff for details.",
    imageUrl: "https://picsum.photos/seed/gcash-ewallet-cashin/400/400",
  },
];

export const MOCK_ORDERS: Order[] = [
  {
    id: "ord-001",
    orderNumber: "KSS-2025-00142",
    storeId: "store-1",
    userId: "user-1",
    status: "out_for_delivery",
    paymentStatus: "paid",
    paymentMethod: "gcash",
    subtotal: 1420,
    deliveryFee: 80,
    total: 1500,
    deliveryAddress: "123 Rizal St., Barangay 5, Caloocan City",
    notes: "Please call before arriving",
    items: [
      { id: "oi-1", orderId: "ord-001", productId: "bev-001", quantity: 24, unitPrice: 28, totalPrice: 672, status: "picked" as const, fulfilledQty: 24 },
      { id: "oi-2", orderId: "ord-001", productId: "noo-001", quantity: 48, unitPrice: 14, totalPrice: 672, status: "picked" as const, fulfilledQty: 48 },
      { id: "oi-3", orderId: "ord-001", productId: "cof-001", quantity: 10, unitPrice: 85, totalPrice: 850, status: "pending" as const },
    ],
    fulfillmentEvents: [],
    createdAt: "2025-01-20T08:30:00Z",
    updatedAt: "2025-01-20T14:00:00Z",
  },
  {
    id: "ord-002",
    orderNumber: "KSS-2025-00141",
    storeId: "store-1",
    userId: "user-1",
    status: "delivered",
    paymentStatus: "paid",
    paymentMethod: "cod",
    subtotal: 2240,
    deliveryFee: 80,
    total: 2320,
    deliveryAddress: "123 Rizal St., Barangay 5, Caloocan City",
    items: [
      { id: "oi-4", orderId: "ord-002", productId: "can-001", quantity: 48, unitPrice: 28, totalPrice: 1344, status: "picked" as const, fulfilledQty: 48 },
      { id: "oi-5", orderId: "ord-002", productId: "con-001", quantity: 12, unitPrice: 62, totalPrice: 744, status: "picked" as const, fulfilledQty: 12 },
      { id: "oi-6", orderId: "ord-002", productId: "per-001", quantity: 24, unitPrice: 22, totalPrice: 528, status: "picked" as const, fulfilledQty: 24 },
    ],
    fulfillmentEvents: [],
    createdAt: "2025-01-17T09:00:00Z",
    updatedAt: "2025-01-18T16:30:00Z",
  },
  {
    id: "ord-003",
    orderNumber: "KSS-2025-00138",
    storeId: "store-1",
    userId: "user-1",
    status: "delivered",
    paymentStatus: "paid",
    paymentMethod: "gcash",
    subtotal: 1890,
    deliveryFee: 80,
    total: 1970,
    deliveryAddress: "123 Rizal St., Barangay 5, Caloocan City",
    items: [],
    fulfillmentEvents: [],
    createdAt: "2025-01-12T10:00:00Z",
    updatedAt: "2025-01-13T15:00:00Z",
  },
];

export const MOCK_NOTIFICATIONS: Notification[] = [
  {
    id: "notif-1",
    userId: "user-1",
    type: "order_out_for_delivery",
    title: "Order on the way!",
    message: "Your order #KSS-2025-00142 is out for delivery. Expected by 5PM today.",
    isRead: false,
    orderId: "ord-001",
    createdAt: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
  },
  {
    id: "notif-2",
    userId: "user-1",
    type: "order_confirmed",
    title: "Order confirmed",
    message: "Your order #KSS-2025-00142 has been confirmed and is being prepared.",
    isRead: false,
    orderId: "ord-001",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 3).toISOString(),
  },
  {
    id: "notif-3",
    userId: "user-1",
    type: "subscription_expiring",
    title: "Subscription renews in 7 days",
    message: "Your Ka Sari-Sari subscription renews on Feb 1. Make sure your payment method is up to date.",
    isRead: true,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
  },
];

export const ADMIN_STATS: AdminStats = {
  totalOrders: 1_847,
  ordersToday: 38,
  revenueToday: 58_420,
  revenueMonth: 1_248_600,
  activeRetailers: 312,
  newRetailersMonth: 24,
  pendingOrders: 14,
  processingOrders: 8,
  outForDelivery: 5,
  lowStockItems: 6,
};

export const ADMIN_RECENT_ORDERS: Order[] = [
  { id: "ord-a1", orderNumber: "KSS-2025-00145", storeId: "s1", userId: "u1", status: "pending", paymentStatus: "paid", paymentMethod: "gcash", subtotal: 1840, deliveryFee: 80, total: 1920, deliveryAddress: "Quezon City", items: [], fulfillmentEvents: [], createdAt: new Date(Date.now() - 1000 * 60 * 15).toISOString(), updatedAt: new Date().toISOString() },
  { id: "ord-a2", orderNumber: "KSS-2025-00144", storeId: "s2", userId: "u2", status: "picking", paymentStatus: "paid", paymentMethod: "gcash", subtotal: 3200, deliveryFee: 80, total: 3280, deliveryAddress: "Marikina City", items: [], fulfillmentEvents: [], createdAt: new Date(Date.now() - 1000 * 60 * 45).toISOString(), updatedAt: new Date().toISOString() },
  { id: "ord-a3", orderNumber: "KSS-2025-00143", storeId: "s3", userId: "u3", status: "packed", paymentStatus: "paid", paymentMethod: "cod", subtotal: 980, deliveryFee: 80, total: 1060, deliveryAddress: "Caloocan City", items: [], fulfillmentEvents: [], createdAt: new Date(Date.now() - 1000 * 60 * 90).toISOString(), updatedAt: new Date().toISOString() },
  { id: "ord-a4", orderNumber: "KSS-2025-00142", storeId: "s4", userId: "u4", status: "out_for_delivery", paymentStatus: "paid", paymentMethod: "gcash", subtotal: 1420, deliveryFee: 80, total: 1500, deliveryAddress: "Caloocan City", items: [], fulfillmentEvents: [], createdAt: new Date(Date.now() - 1000 * 60 * 120).toISOString(), updatedAt: new Date().toISOString() },
  { id: "ord-a5", orderNumber: "KSS-2025-00141", storeId: "s5", userId: "u5", status: "delivered", paymentStatus: "paid", paymentMethod: "gcash", subtotal: 2240, deliveryFee: 80, total: 2320, deliveryAddress: "Pasig City", items: [], fulfillmentEvents: [], createdAt: new Date(Date.now() - 1000 * 60 * 180).toISOString(), updatedAt: new Date().toISOString() },
];

// ─── Suppliers ────────────────────────────────────────────────────────────────

export const SUPPLIERS: Supplier[] = [
  {
    id: "sup-1",
    name: "PhilBev Distribution Inc.",
    contactName: "Roberto Aquino",
    phone: "+63 2 8888 1234",
    email: "roberto@philbev.com",
    address: "123 Industrial Ave, Valenzuela City",
    city: "Valenzuela City",
    status: "active",
    paymentTerms: "30 days NET",
    leadTimeDays: 3,
    totalPurchases: 2_450_000,
    lastOrderDate: "2025-01-15T00:00:00Z",
    categories: ["Beverages", "Coffee & Milo"],
    createdAt: "2023-06-01T00:00:00Z",
  },
  {
    id: "sup-2",
    name: "Lucky Me Foods Corp",
    contactName: "Sandra Villanueva",
    phone: "+63 2 8777 9900",
    email: "orders@luckyme.com",
    address: "45 Commerce Blvd, Taguig City",
    city: "Taguig City",
    status: "active",
    paymentTerms: "COD",
    leadTimeDays: 2,
    totalPurchases: 1_820_000,
    lastOrderDate: "2025-01-18T00:00:00Z",
    categories: ["Instant Noodles", "Snacks & Chips"],
    createdAt: "2023-08-15T00:00:00Z",
  },
  {
    id: "sup-3",
    name: "Del Monte Philippines",
    contactName: "Carlos Mendoza",
    phone: "+63 2 8999 5678",
    email: "c.mendoza@delmonte.ph",
    address: "789 Bulacan Industrial Complex, Bulacan",
    city: "Malolos City",
    status: "active",
    paymentTerms: "15 days NET",
    leadTimeDays: 4,
    totalPurchases: 980_000,
    lastOrderDate: "2025-01-10T00:00:00Z",
    categories: ["Canned Goods", "Condiments & Sauces"],
    createdAt: "2023-11-20T00:00:00Z",
  },
  {
    id: "sup-4",
    name: "Procter & Gamble Philippines",
    contactName: "Maricel Santos",
    phone: "+63 2 8555 4321",
    email: "ph.orders@pg.com",
    address: "One Corporate Center, Ortigas, Pasig City",
    city: "Pasig City",
    status: "active",
    paymentTerms: "45 days NET",
    leadTimeDays: 5,
    totalPurchases: 3_200_000,
    lastOrderDate: "2025-01-20T00:00:00Z",
    categories: ["Personal Care", "Laundry & Cleaning"],
    createdAt: "2023-04-01T00:00:00Z",
  },
  {
    id: "sup-5",
    name: "Mega Global Corp",
    contactName: "Jaime Reyes",
    phone: "+63 2 8333 7788",
    email: "jaime@megaglobal.ph",
    address: "560 EDSA, Balintawak, Quezon City",
    city: "Quezon City",
    status: "active",
    paymentTerms: "30 days NET",
    leadTimeDays: 3,
    totalPurchases: 755_000,
    lastOrderDate: "2025-01-12T00:00:00Z",
    categories: ["Canned Goods"],
    createdAt: "2024-01-10T00:00:00Z",
  },
];

// ─── Drivers ──────────────────────────────────────────────────────────────────

export const DRIVERS: Driver[] = [
  {
    id: "drv-1",
    name: "Rodrigo Delos Santos",
    phone: "+63 917 111 2222",
    licenseNumber: "D10-23-456789",
    vehicleType: "van",
    vehiclePlate: "AAA 1234",
    status: "on_route",
    rating: 4.9,
    deliveriesTotal: 1247,
    deliveriesToday: 8,
    currentRouteId: "route-1",
    avatarInitials: "RD",
    createdAt: "2023-06-15T00:00:00Z",
  },
  {
    id: "drv-2",
    name: "Benjamin Cruz",
    phone: "+63 918 222 3333",
    licenseNumber: "D10-22-112233",
    vehicleType: "van",
    vehiclePlate: "BBB 5678",
    status: "on_route",
    rating: 4.7,
    deliveriesTotal: 892,
    deliveriesToday: 5,
    currentRouteId: "route-2",
    avatarInitials: "BC",
    createdAt: "2023-09-01T00:00:00Z",
  },
  {
    id: "drv-3",
    name: "Antonio Lim",
    phone: "+63 919 333 4444",
    licenseNumber: "D10-21-998877",
    vehicleType: "tricycle",
    vehiclePlate: "CC 9012",
    status: "active",
    rating: 4.8,
    deliveriesTotal: 2105,
    deliveriesToday: 0,
    avatarInitials: "AL",
    createdAt: "2022-03-20T00:00:00Z",
  },
  {
    id: "drv-4",
    name: "Mark Villanueva",
    phone: "+63 920 444 5555",
    licenseNumber: "D10-23-667788",
    vehicleType: "motorcycle",
    vehiclePlate: "DDD 3456",
    status: "off_duty",
    rating: 4.6,
    deliveriesTotal: 456,
    deliveriesToday: 0,
    avatarInitials: "MV",
    createdAt: "2024-01-05T00:00:00Z",
  },
  {
    id: "drv-5",
    name: "Jose Fernandez",
    phone: "+63 921 555 6666",
    licenseNumber: "D10-20-334455",
    vehicleType: "van",
    vehiclePlate: "EEE 7890",
    status: "active",
    rating: 4.95,
    deliveriesTotal: 3420,
    deliveriesToday: 0,
    avatarInitials: "JF",
    createdAt: "2021-11-10T00:00:00Z",
  },
];

// ─── Routes ───────────────────────────────────────────────────────────────────

export const ROUTES: Route[] = [
  {
    id: "route-1",
    name: "Caloocan North",
    driverId: "drv-1",
    status: "active",
    stops: 12,
    completedStops: 7,
    distance: "34 km",
    estimatedDuration: "4 hrs",
    orderIds: ["ord-a1", "ord-a2", "ord-a4"],
    startedAt: new Date(Date.now() - 1000 * 60 * 120).toISOString(),
    createdAt: new Date(Date.now() - 1000 * 60 * 180).toISOString(),
  },
  {
    id: "route-2",
    name: "Marikina - Pasig",
    driverId: "drv-2",
    status: "active",
    stops: 9,
    completedStops: 4,
    distance: "28 km",
    estimatedDuration: "3.5 hrs",
    orderIds: ["ord-a3", "ord-a5"],
    startedAt: new Date(Date.now() - 1000 * 60 * 90).toISOString(),
    createdAt: new Date(Date.now() - 1000 * 60 * 150).toISOString(),
  },
  {
    id: "route-3",
    name: "Quezon City South",
    status: "planned",
    stops: 15,
    completedStops: 0,
    distance: "41 km",
    estimatedDuration: "5 hrs",
    orderIds: [],
    createdAt: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
  },
];

// ─── Purchase Orders ──────────────────────────────────────────────────────────

export const PURCHASE_ORDERS: PurchaseOrder[] = [
  {
    id: "po-001",
    poNumber: "PO-2025-0089",
    supplierId: "sup-1",
    status: "confirmed",
    items: [
      { id: "poi-1", purchaseOrderId: "po-001", productId: "bev-001", productName: "Coca-Cola Regular 330ml", sku: "CC-330-REG", orderedQty: 960, receivedQty: 0, unitCost: 22, totalCost: 21120 },
      { id: "poi-2", purchaseOrderId: "po-001", productId: "bev-003", productName: "Wilkins Pure Distilled Water 500ml", sku: "WLK-500-PUR", orderedQty: 480, receivedQty: 0, unitCost: 9, totalCost: 4320 },
    ],
    subtotal: 25440,
    total: 25440,
    expectedDate: new Date(Date.now() + 1000 * 60 * 60 * 48).toISOString(),
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 60 * 12).toISOString(),
  },
  {
    id: "po-002",
    poNumber: "PO-2025-0088",
    supplierId: "sup-2",
    status: "received",
    items: [
      { id: "poi-3", purchaseOrderId: "po-002", productId: "noo-001", productName: "Lucky Me Pancit Canton Original 65g", sku: "LM-PC-ORI", orderedQty: 480, receivedQty: 480, unitCost: 10, totalCost: 4800 },
    ],
    subtotal: 4800,
    total: 4800,
    expectedDate: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
    receivedDate: new Date(Date.now() - 1000 * 60 * 60 * 12).toISOString(),
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 72).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 60 * 12).toISOString(),
  },
  {
    id: "po-003",
    poNumber: "PO-2025-0087",
    supplierId: "sup-4",
    status: "sent",
    items: [
      { id: "poi-4", purchaseOrderId: "po-003", productId: "per-001", productName: "Safeguard Classic Antibacterial Bar Soap 135g", sku: "SFG-CLA-135", orderedQty: 480, receivedQty: 0, unitCost: 17, totalCost: 8160 },
      { id: "poi-5", purchaseOrderId: "po-003", productId: "lau-001", productName: "Surf Powder Detergent 66g x 6", sku: "SURF-PWD-66", orderedQty: 240, receivedQty: 0, unitCost: 38, totalCost: 9120 },
    ],
    subtotal: 17280,
    total: 17280,
    expectedDate: new Date(Date.now() + 1000 * 60 * 60 * 72).toISOString(),
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 48).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 60 * 48).toISOString(),
  },
];

// ─── Promotions ───────────────────────────────────────────────────────────────

export const PROMOTIONS: Promotion[] = [
  {
    id: "promo-1",
    title: "Flash Sale: Beverages",
    description: "Get 20% off all beverage products. Stock up for the week!",
    discountType: "percentage",
    discountValue: 20,
    minimumOrder: 500,
    categoryIds: ["cat-06"],
    startDate: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(),
    endDate: new Date(Date.now() + 1000 * 60 * 60 * 22).toISOString(),
    status: "active",
    usageCount: 47,
    maxUsage: 100,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
  },
  {
    id: "promo-2",
    title: "Bundle Deal: Snacks Bonanza",
    description: "Buy 100 packs of any chips, get 10% off your entire order.",
    discountType: "percentage",
    discountValue: 10,
    minimumOrder: 1000,
    categoryIds: ["cat-03"],
    startDate: new Date(Date.now() - 1000 * 60 * 60 * 48).toISOString(),
    endDate: new Date(Date.now() + 1000 * 60 * 60 * 48).toISOString(),
    status: "active",
    usageCount: 23,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 72).toISOString(),
  },
  {
    id: "promo-3",
    title: "Free Delivery Weekend",
    description: "Free delivery on all orders above PHP 2,000 this weekend.",
    discountType: "fixed",
    discountValue: 80,
    minimumOrder: 2000,
    startDate: new Date(Date.now() + 1000 * 60 * 60 * 24).toISOString(),
    endDate: new Date(Date.now() + 1000 * 60 * 60 * 72).toISOString(),
    status: "scheduled",
    usageCount: 0,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 12).toISOString(),
  },
  {
    id: "promo-4",
    title: "New Year Promo",
    description: "PHP 100 off orders above PHP 2,500.",
    discountType: "fixed",
    discountValue: 100,
    minimumOrder: 2500,
    startDate: "2025-01-01T00:00:00Z",
    endDate: "2025-01-15T23:59:59Z",
    status: "ended",
    usageCount: 156,
    createdAt: "2024-12-28T00:00:00Z",
  },
];

// ─── Pick Lists ───────────────────────────────────────────────────────────────

export const PICK_LISTS: PickList[] = [
  {
    id: "pl-001",
    orderId: "ord-a1",
    orderNumber: "KSS-2025-00145",
    status: "in_progress",
    assignedTo: "Warehouse Staff A",
    items: [
      { id: "pli-1", productId: "bev-001", productName: "Coca-Cola Regular 330ml", sku: "CC-330-REG", quantity: 24, pickedQty: 24, bin: "A1-S3-B2", status: "picked" },
      { id: "pli-2", productId: "cof-001", productName: "Nescafe 3-in-1 Original Blend 20g x 10", sku: "NES-3IN1-ORI", quantity: 10, pickedQty: 5, bin: "B2-S1-B4", status: "partial" },
      { id: "pli-3", productId: "can-001", productName: "555 Sardines in Tomato Sauce 155g", sku: "555-SAR-TOM", quantity: 24, pickedQty: 0, bin: "C3-S2-B1", status: "pending" },
    ],
    createdAt: new Date(Date.now() - 1000 * 60 * 90).toISOString(),
  },
  {
    id: "pl-002",
    orderId: "ord-a2",
    orderNumber: "KSS-2025-00144",
    status: "open",
    items: [
      { id: "pli-4", productId: "noo-001", productName: "Lucky Me Pancit Canton Original 65g", sku: "LM-PC-ORI", quantity: 48, pickedQty: 0, bin: "A2-S4-B3", status: "pending" },
      { id: "pli-5", productId: "per-001", productName: "Safeguard Classic Antibacterial Bar Soap 135g", sku: "SFG-CLA-135", quantity: 48, pickedQty: 0, bin: "D1-S2-B5", status: "pending" },
    ],
    createdAt: new Date(Date.now() - 1000 * 60 * 45).toISOString(),
  },
  {
    id: "pl-003",
    orderId: "ord-a3",
    orderNumber: "KSS-2025-00143",
    status: "completed",
    assignedTo: "Warehouse Staff B",
    items: [
      { id: "pli-6", productId: "con-001", productName: "Silver Swan Soy Sauce 1L", sku: "SS-SOY-1L", quantity: 12, pickedQty: 12, bin: "C1-S3-B2", status: "picked" },
      { id: "pli-7", productId: "lau-001", productName: "Surf Powder Detergent 66g x 6", sku: "SURF-PWD-66", quantity: 12, pickedQty: 12, bin: "D2-S1-B1", status: "picked" },
    ],
    createdAt: new Date(Date.now() - 1000 * 60 * 180).toISOString(),
    completedAt: new Date(Date.now() - 1000 * 60 * 60).toISOString(),
  },
];

// ─── Goods Receipts ───────────────────────────────────────────────────────────

export const GOODS_RECEIPTS: GoodsReceipt[] = [
  {
    id: "gr-001",
    purchaseOrderId: "po-001",
    poNumber: "PO-2025-0089",
    supplierName: "PhilBev Distribution Inc.",
    items: [
      { productName: "Coca-Cola Regular 330ml", sku: "CC-330-REG", expectedQty: 960, receivedQty: 0 },
      { productName: "Wilkins Pure Distilled Water 500ml", sku: "WLK-500-PUR", expectedQty: 480, receivedQty: 0 },
    ],
    status: "pending",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
  },
];
